// APPEARANCE: 518 entries
export const APPEARANCE = [
  { label: 'Null human', nwscript: 'APPEARANCE_TYPE_INVISIBLE_HUMAN_MALE', wingTail: 'none' },
  { label: 'Allip', nwscript: 'APPEARANCE_TYPE_ALLIP', wingTail: 'none' },
  { label: 'Aranea', nwscript: 'APPEARANCE_TYPE_ARANEA', wingTail: 'none' },
  { label: 'Archery Target', nwscript: 'APPEARANCE_TYPE_ARCH_TARGET', wingTail: 'none' },
  { label: 'Asabi Chieftain', nwscript: 'APPEARANCE_TYPE_ASABI_CHIEFTAIN', wingTail: 'none' },
  { label: 'Asabi Shaman', nwscript: 'APPEARANCE_TYPE_ASABI_SHAMAN', wingTail: 'none' },
  { label: 'Asabi Warrior', nwscript: 'APPEARANCE_TYPE_ASABI_WARRIOR', wingTail: 'none' },
  { label: 'Azer, Female', nwscript: 'APPEARANCE_TYPE_AZER_FEMALE', wingTail: 'none' },
  { label: 'Azer, Male', nwscript: 'APPEARANCE_TYPE_AZER_MALE', wingTail: 'none' },
  { label: 'Badger', nwscript: 'APPEARANCE_TYPE_BADGER', wingTail: 'none' },
  { label: 'Badger, Dire', nwscript: 'APPEARANCE_TYPE_BADGER_DIRE', wingTail: 'none' },
  { label: 'Balor', nwscript: 'APPEARANCE_TYPE_BALOR', wingTail: 'none' },
  { label: 'Bartender', nwscript: 'APPEARANCE_TYPE_BARTENDER', wingTail: 'none' },
  { label: 'Basilisk', nwscript: 'APPEARANCE_TYPE_BASILISK', wingTail: 'none' },
  { label: 'Bat', nwscript: 'APPEARANCE_TYPE_BAT', wingTail: 'none' },
  { label: 'Battle Horror', nwscript: 'APPEARANCE_TYPE_BAT_HORROR', wingTail: 'none' },
  { label: 'Bear, Black', nwscript: 'APPEARANCE_TYPE_BEAR_BLACK', wingTail: 'none' },
  { label: 'Bear, Brown', nwscript: 'APPEARANCE_TYPE_BEAR_BROWN', wingTail: 'none' },
  { label: 'Bear, Dire', nwscript: 'APPEARANCE_TYPE_BEAR_DIRE', wingTail: 'none' },
  { label: 'Bear, Grizzly', nwscript: 'APPEARANCE_TYPE_BEAR_KODIAK', wingTail: 'none' },
  { label: 'Bear, Polar', nwscript: 'APPEARANCE_TYPE_BEAR_POLAR', wingTail: 'none' },
  { label: 'Beetle, Fire', nwscript: 'APPEARANCE_TYPE_BEETLE_FIRE', wingTail: 'none' },
  { label: 'Beetle, Slicer', nwscript: 'APPEARANCE_TYPE_BEETLE_SLICER', wingTail: 'none' },
  { label: 'Beetle, Stag', nwscript: 'APPEARANCE_TYPE_BEETLE_STAG', wingTail: 'none' },
  { label: 'Beetle, Stink', nwscript: 'APPEARANCE_TYPE_BEETLE_STINK', wingTail: 'none' },
  { label: 'Beggar', nwscript: 'APPEARANCE_TYPE_BEGGER', wingTail: 'none' },
  { label: 'Beholder', nwscript: 'APPEARANCE_TYPE_BEHOLDER', wingTail: 'none' },
  { label: 'Beholder Tyrant', nwscript: 'APPEARANCE_TYPE_BEHOLDER_MOTHER', wingTail: 'none' },
  { label: 'Beholder, Eyeball', nwscript: 'APPEARANCE_TYPE_BEHOLDER_EYEBALL', wingTail: 'none' },
  { label: 'Beholder, G\'Zhorb', nwscript: '299', wingTail: 'none' },
  { label: 'Beholder, Mage', nwscript: 'APPEARANCE_TYPE_BEHOLDER_MAGE', wingTail: 'none' },
  { label: 'Bloodsailor', nwscript: 'APPEARANCE_TYPE_BLOOD_SAILER', wingTail: 'none' },
  { label: 'Boar', nwscript: 'APPEARANCE_TYPE_BOAR', wingTail: 'none' },
  { label: 'Boar, Dire', nwscript: 'APPEARANCE_TYPE_BOAR_DIRE', wingTail: 'none' },
  { label: 'Bodak', nwscript: 'APPEARANCE_TYPE_BODAK', wingTail: 'none' },
  { label: 'Bugbear A', nwscript: 'APPEARANCE_TYPE_BUGBEAR_A', wingTail: 'none' },
  { label: 'Bugbear B', nwscript: 'APPEARANCE_TYPE_BUGBEAR_B', wingTail: 'none' },
  { label: 'Bugbear, Chieftain A', nwscript: 'APPEARANCE_TYPE_BUGBEAR_CHIEFTAIN_A', wingTail: 'none' },
  { label: 'Bugbear, Chieftain B', nwscript: 'APPEARANCE_TYPE_BUGBEAR_CHIEFTAIN_B', wingTail: 'none' },
  { label: 'Bugbear, Shaman A', nwscript: 'APPEARANCE_TYPE_BUGBEAR_SHAMAN_A', wingTail: 'none' },
  { label: 'Bugbear, Shaman B', nwscript: 'APPEARANCE_TYPE_BUGBEAR_SHAMAN_B', wingTail: 'none' },
  { label: 'Bulette', nwscript: 'APPEARANCE_TYPE_BULETTE', wingTail: 'none' },
  { label: 'Caladnei', nwscript: '450', wingTail: 'none' },
  { label: 'Candelabra', nwscript: 'APPEARANCE_TYPE_OBJECT_CANDLE', wingTail: 'none' },
  { label: 'Cat, Cougar', nwscript: 'APPEARANCE_TYPE_CAT_COUGAR', wingTail: 'none' },
  { label: 'Cat, Crag Cat', nwscript: 'APPEARANCE_TYPE_CAT_CRAG_CAT', wingTail: 'none' },
  { label: 'Cat, Dire Tiger', nwscript: 'APPEARANCE_TYPE_CAT_CAT_DIRE', wingTail: 'none' },
  { label: 'Cat, Jaguar', nwscript: 'APPEARANCE_TYPE_CAT_JAGUAR', wingTail: 'none' },
  { label: 'Cat, Krenshar', nwscript: 'APPEARANCE_TYPE_CAT_KRENSHAR', wingTail: 'none' },
  { label: 'Cat, Leopard', nwscript: 'APPEARANCE_TYPE_CAT_LEOPARD', wingTail: 'none' },
  { label: 'Cat, Lion', nwscript: 'APPEARANCE_TYPE_CAT_LION', wingTail: 'none' },
  { label: 'Cat, Malar', nwscript: 'APPEARANCE_TYPE_CAT_MPANTHER', wingTail: 'none' },
  { label: 'Cat, Panther', nwscript: 'APPEARANCE_TYPE_CAT_PANTHER', wingTail: 'none' },
  { label: 'Celestial Avenger, Male', nwscript: 'APPEARANCE_TYPE_RAKSHASA_BEAR_MALE', wingTail: 'none' },
  { label: 'Chair', nwscript: 'APPEARANCE_TYPE_OBJECT_CHAIR', wingTail: 'none' },
  { label: 'Chest', nwscript: 'APPEARANCE_TYPE_OBJECT_CHEST', wingTail: 'none' },
  { label: 'Chicken', nwscript: 'APPEARANCE_TYPE_CHICKEN', wingTail: 'none' },
  { label: 'Child, Female', nwscript: 'APPEARANCE_TYPE_KID_FEMALE', wingTail: 'none' },
  { label: 'Child, Male', nwscript: 'APPEARANCE_TYPE_KID_MALE', wingTail: 'none' },
  { label: 'Cockatrice', nwscript: 'APPEARANCE_TYPE_COCKATRICE', wingTail: 'none' },
  { label: 'Combat Dummy', nwscript: 'APPEARANCE_TYPE_COMBAT_DUMMY', wingTail: 'none' },
  { label: 'Convict', nwscript: 'APPEARANCE_TYPE_CONVICT', wingTail: 'none' },
  { label: 'Cow', nwscript: 'APPEARANCE_TYPE_COW', wingTail: 'none' },
  { label: 'Cult Member', nwscript: 'APPEARANCE_TYPE_CULT_MEMBER', wingTail: 'none' },
  { label: 'Curst Swordsman', nwscript: '16', wingTail: 'none' },
  { label: 'Deep Rothe', nwscript: 'APPEARANCE_TYPE_DEEP_ROTHE', wingTail: 'none' },
  { label: 'Deer', nwscript: 'APPEARANCE_TYPE_DEER', wingTail: 'none' },
  { label: 'Deer, Stag', nwscript: 'APPEARANCE_TYPE_DEER_STAG', wingTail: 'none' },
  { label: 'Demilich', nwscript: 'APPEARANCE_TYPE_DEMI_LICH', wingTail: 'none' },
  { label: 'Demon, Bebilith', nwscript: 'APPEARANCE_TYPE_SPIDER_DEMON', wingTail: 'none' },
  { label: 'Devil', nwscript: 'APPEARANCE_TYPE_DEVIL', wingTail: 'none' },
  { label: 'Dog', nwscript: 'APPEARANCE_TYPE_DOG', wingTail: 'none' },
  { label: 'Dog, Blink Dog', nwscript: 'APPEARANCE_TYPE_DOG_BLINKDOG', wingTail: 'none' },
  { label: 'Dog, Dire Wolf', nwscript: 'APPEARANCE_TYPE_DOG_DIRE_WOLF', wingTail: 'none' },
  { label: 'Dog, Fenhound', nwscript: 'APPEARANCE_TYPE_DOG_FENHOUND', wingTail: 'none' },
  { label: 'Dog, Hell Hound', nwscript: 'APPEARANCE_TYPE_DOG_HELL_HOUND', wingTail: 'none' },
  { label: 'Dog, Shadow Mastiff', nwscript: 'APPEARANCE_TYPE_DOG_SHADOW_MASTIF', wingTail: 'none' },
  { label: 'Dog, Winter Wolf', nwscript: 'APPEARANCE_TYPE_DOG_WINTER_WOLF', wingTail: 'none' },
  { label: 'Dog, Wolf', nwscript: 'APPEARANCE_TYPE_DOG_WOLF', wingTail: 'none' },
  { label: 'Dog, Worg', nwscript: 'APPEARANCE_TYPE_DOG_WORG', wingTail: 'none' },
  { label: 'Doom Knight', nwscript: 'APPEARANCE_TYPE_DOOM_KNIGHT', wingTail: 'none' },
  { label: 'Dracolich', nwscript: 'APPEARANCE_TYPE_DRACOLICH', wingTail: 'none' },
  { label: 'Dragon, Black', nwscript: 'APPEARANCE_TYPE_DRAGON_BLACK', wingTail: 'none' },
  { label: 'Dragon, Blue', nwscript: 'APPEARANCE_TYPE_DRAGON_BLUE', wingTail: 'none' },
  { label: 'Dragon, Brass', nwscript: 'APPEARANCE_TYPE_DRAGON_BRASS', wingTail: 'none' },
  { label: 'Dragon, Bronze', nwscript: 'APPEARANCE_TYPE_DRAGON_BRONZE', wingTail: 'none' },
  { label: 'Dragon, Copper', nwscript: 'APPEARANCE_TYPE_DRAGON_COPPER', wingTail: 'none' },
  { label: 'Dragon, Gold', nwscript: 'APPEARANCE_TYPE_DRAGON_GOLD', wingTail: 'none' },
  { label: 'Dragon, Green', nwscript: 'APPEARANCE_TYPE_DRAGON_GREEN', wingTail: 'none' },
  { label: 'Dragon, Mist', nwscript: '118', wingTail: 'none' },
  { label: 'Dragon, Prismatic', nwscript: 'APPEARANCE_TYPE_DRAGON_PRIS', wingTail: 'none' },
  { label: 'Dragon, Red', nwscript: 'APPEARANCE_TYPE_DRAGON_RED', wingTail: 'none' },
  { label: 'Dragon, Shadow', nwscript: 'APPEARANCE_TYPE_DRAGON_SHADOW', wingTail: 'none' },
  { label: 'Dragon, Silver', nwscript: 'APPEARANCE_TYPE_DRAGON_SILVER', wingTail: 'none' },
  { label: 'Dragon, White', nwscript: 'APPEARANCE_TYPE_DRAGON_WHITE', wingTail: 'none' },
  { label: 'Drider, female', nwscript: 'APPEARANCE_TYPE_DRIDER_FEMALE', wingTail: 'none' },
  { label: 'Drider, male', nwscript: 'APPEARANCE_TYPE_DRIDER', wingTail: 'none' },
  { label: 'Drider, Chief', nwscript: 'APPEARANCE_TYPE_DRIDER_CHIEF', wingTail: 'none' },
  { label: 'Drow Boat', nwscript: 'APPEARANCE_TYPE_OBJECT_BOAT', wingTail: 'none' },
  { label: 'Drow Cleric', nwscript: 'APPEARANCE_TYPE_DROW_CLERIC', wingTail: 'none' },
  { label: 'Drow Fighter', nwscript: 'APPEARANCE_TYPE_DROW_FIGHTER', wingTail: 'none' },
  { label: 'Drow, Fighter 2', nwscript: 'APPEARANCE_TYPE_DROW_WARRIOR_1', wingTail: 'none' },
  { label: 'Drow, Fighter 3', nwscript: 'APPEARANCE_TYPE_DROW_WARRIOR_2', wingTail: 'none' },
  { label: 'Drow, Fighter 4', nwscript: 'APPEARANCE_TYPE_DROW_WARRIOR_3', wingTail: 'none' },
  { label: 'Drow, Matron', nwscript: 'APPEARANCE_TYPE_DROW_MATRON', wingTail: 'none' },
  { label: 'Drow, Rebel', nwscript: 'APPEARANCE_TYPE_DROW_SLAVE', wingTail: 'none' },
  { label: 'Drow, Red Sister 1', nwscript: 'APPEARANCE_TYPE_DROW_FEMALE_1', wingTail: 'none' },
  { label: 'Drow, Red Sister 2', nwscript: 'APPEARANCE_TYPE_DROW_FEMALE_2', wingTail: 'none' },
  { label: 'Drow, Wizard', nwscript: 'APPEARANCE_TYPE_DROW_WIZARD', wingTail: 'none' },
  { label: 'Dryad', nwscript: 'APPEARANCE_TYPE_DRYAD', wingTail: 'none' },
  { label: 'Duergar, Chief', nwscript: 'APPEARANCE_TYPE_DUERGAR_CHIEF', wingTail: 'none' },
  { label: 'Duergar Cleric', nwscript: 'APPEARANCE_TYPE_DRUEGAR_CLERIC', wingTail: 'none' },
  { label: 'Duergar Fighter', nwscript: 'APPEARANCE_TYPE_DRUEGAR_FIGHTER', wingTail: 'none' },
  { label: 'Duergar, Slaver', nwscript: 'APPEARANCE_TYPE_DUERGAR_SLAVE', wingTail: 'none' },
  { label: 'Dwarf', nwscript: 'APPEARANCE_TYPE_DWARF', wingTail: 'both' },
  { label: 'Dwarf mounted, female', nwscript: '482', wingTail: 'both' },
  { label: 'Dwarf mounted, male', nwscript: '483', wingTail: 'both' },
  { label: 'Dwarf, female', nwscript: 'APPEARANCE_TYPE_DWARF_NPC_FEMALE', wingTail: 'none' },
  { label: 'Dwarf, male', nwscript: 'APPEARANCE_TYPE_DWARF_NPC_MALE', wingTail: 'none' },
  { label: 'Elemental, Air', nwscript: 'APPEARANCE_TYPE_ELEMENTAL_AIR', wingTail: 'none' },
  { label: 'Elemental, Air Elder', nwscript: 'APPEARANCE_TYPE_ELEMENTAL_AIR_ELDER', wingTail: 'none' },
  { label: 'Elemental, Earth', nwscript: 'APPEARANCE_TYPE_ELEMENTAL_EARTH', wingTail: 'none' },
  { label: 'Elemental, Earth Elder', nwscript: 'APPEARANCE_TYPE_ELEMENTAL_EARTH_ELDER', wingTail: 'none' },
  { label: 'Elemental, Fire', nwscript: 'APPEARANCE_TYPE_ELEMENTAL_FIRE', wingTail: 'none' },
  { label: 'Elemental, Fire Elder', nwscript: 'APPEARANCE_TYPE_ELEMENTAL_FIRE_ELDER', wingTail: 'none' },
  { label: 'Elemental, Water', nwscript: 'APPEARANCE_TYPE_ELEMENTAL_WATER', wingTail: 'none' },
  { label: 'Elemental, Water Elder', nwscript: 'APPEARANCE_TYPE_ELEMENTAL_WATER_ELDER', wingTail: 'none' },
  { label: 'Elf', nwscript: 'APPEARANCE_TYPE_ELF', wingTail: 'both' },
  { label: 'Elf mounted, female', nwscript: '484', wingTail: 'both' },
  { label: 'Elf mounted, male', nwscript: '485', wingTail: 'both' },
  { label: 'Elf, female', nwscript: 'APPEARANCE_TYPE_ELF_NPC_FEMALE', wingTail: 'none' },
  { label: 'Elf, male 1', nwscript: 'APPEARANCE_TYPE_ELF_NPC_MALE_01', wingTail: 'none' },
  { label: 'Elf, male 2', nwscript: 'APPEARANCE_TYPE_ELF_NPC_MALE_02', wingTail: 'none' },
  { label: 'Ettercap', nwscript: 'APPEARANCE_TYPE_ETTERCAP', wingTail: 'none' },
  { label: 'Ettin', nwscript: 'APPEARANCE_TYPE_ETTIN', wingTail: 'none' },
  { label: 'Faerie Dragon', nwscript: 'APPEARANCE_TYPE_FAERIE_DRAGON', wingTail: 'none' },
  { label: 'Fairy', nwscript: 'APPEARANCE_TYPE_FAIRY', wingTail: 'none' },
  { label: 'Falcon', nwscript: 'APPEARANCE_TYPE_FALCON', wingTail: 'none' },
  { label: 'Female 1', nwscript: 'APPEARANCE_TYPE_FEMALE_01', wingTail: 'none' },
  { label: 'Female 2', nwscript: 'APPEARANCE_TYPE_FEMALE_02', wingTail: 'none' },
  { label: 'Female 3', nwscript: 'APPEARANCE_TYPE_FEMALE_03', wingTail: 'none' },
  { label: 'Female 4', nwscript: 'APPEARANCE_TYPE_FEMALE_04', wingTail: 'none' },
  { label: 'Flame, small', nwscript: 'APPEARANCE_TYPE_OBJECT_FLAME_SMALL', wingTail: 'none' },
  { label: 'Flame, medium', nwscript: 'APPEARANCE_TYPE_OBJECT_FLAME_MEDIUM', wingTail: 'none' },
  { label: 'Flame, large', nwscript: 'APPEARANCE_TYPE_OBJECT_FLAME_LARGE', wingTail: 'none' },
  { label: 'Formian Myrmarch', nwscript: 'APPEARANCE_TYPE_FORMIAN_MYRMARCH', wingTail: 'none' },
  { label: 'Formian Queen', nwscript: 'APPEARANCE_TYPE_FORMIAN_QUEEN', wingTail: 'none' },
  { label: 'Formian Warrior', nwscript: 'APPEARANCE_TYPE_FORMIAN_WARRIOR', wingTail: 'none' },
  { label: 'Formian Worker', nwscript: 'APPEARANCE_TYPE_FORMIAN_WORKER', wingTail: 'none' },
  { label: 'Gargoyle', nwscript: 'APPEARANCE_TYPE_GARGOYLE', wingTail: 'none' },
  { label: 'Gelatinous Cube', nwscript: 'APPEARANCE_TYPE_GELATINOUS_CUBE', wingTail: 'none' },
  { label: 'Ghast', nwscript: 'APPEARANCE_TYPE_GHAST', wingTail: 'none' },
  { label: 'Ghoul', nwscript: 'APPEARANCE_TYPE_GHOUL', wingTail: 'none' },
  { label: 'Ghoul Lord', nwscript: 'APPEARANCE_TYPE_GHOUL_LORD', wingTail: 'none' },
  { label: 'Giant, Fire', nwscript: 'APPEARANCE_TYPE_GIANT_FIRE', wingTail: 'none' },
  { label: 'Giant, Fire (Female)', nwscript: 'APPEARANCE_TYPE_GIANT_FIRE_FEMALE', wingTail: 'none' },
  { label: 'Giant, Frost', nwscript: 'APPEARANCE_TYPE_GIANT_FROST', wingTail: 'none' },
  { label: 'Giant, Frost (Female)', nwscript: 'APPEARANCE_TYPE_GIANT_FROST_FEMALE', wingTail: 'none' },
  { label: 'Giant, Hill', nwscript: 'APPEARANCE_TYPE_GIANT_HILL', wingTail: 'none' },
  { label: 'Giant, Mountain', nwscript: 'APPEARANCE_TYPE_GIANT_MOUNTAIN', wingTail: 'none' },
  { label: 'Gnoll', nwscript: 'APPEARANCE_TYPE_GNOLL_WARRIOR', wingTail: 'none' },
  { label: 'Gnoll, Shaman', nwscript: 'APPEARANCE_TYPE_GNOLL_WIZ', wingTail: 'none' },
  { label: 'Gnome', nwscript: 'APPEARANCE_TYPE_GNOME', wingTail: 'both' },
  { label: 'Gnome mounted, female', nwscript: '486', wingTail: 'both' },
  { label: 'Gnome mounted, male', nwscript: '487', wingTail: 'both' },
  { label: 'Gnome, female', nwscript: 'APPEARANCE_TYPE_GNOME_NPC_FEMALE', wingTail: 'none' },
  { label: 'Gnome, male', nwscript: 'APPEARANCE_TYPE_GNOME_NPC_MALE', wingTail: 'none' },
  { label: 'Goblin A', nwscript: 'APPEARANCE_TYPE_GOBLIN_A', wingTail: 'none' },
  { label: 'Goblin B', nwscript: 'APPEARANCE_TYPE_GOBLIN_B', wingTail: 'none' },
  { label: 'Goblin, Chieftain A', nwscript: 'APPEARANCE_TYPE_GOBLIN_CHIEF_A', wingTail: 'none' },
  { label: 'Goblin, Chieftain B', nwscript: 'APPEARANCE_TYPE_GOBLIN_CHIEF_B', wingTail: 'none' },
  { label: 'Goblin, Shaman A', nwscript: 'APPEARANCE_TYPE_GOBLIN_SHAMAN_A', wingTail: 'none' },
  { label: 'Goblin, Shaman B', nwscript: 'APPEARANCE_TYPE_GOBLIN_SHAMAN_B', wingTail: 'none' },
  { label: 'Golem, Adamantium', nwscript: 'APPEARANCE_TYPE_GOLEM_ADAMANTIUM', wingTail: 'none' },
  { label: 'Golem, Bone', nwscript: 'APPEARANCE_TYPE_GOLEM_BONE', wingTail: 'none' },
  { label: 'Golem, Clay', nwscript: 'APPEARANCE_TYPE_GOLEM_CLAY', wingTail: 'none' },
  { label: 'Golem, Demonflesh', nwscript: 'APPEARANCE_TYPE_GOLEM_DEMONFLESH', wingTail: 'none' },
  { label: 'Golem, Diamond', nwscript: '149', wingTail: 'none' },
  { label: 'Golem, Dwarf', nwscript: 'APPEARANCE_TYPE_DWARF_GOLEM', wingTail: 'both' },
  { label: 'Golem, Emerald', nwscript: '169', wingTail: 'none' },
  { label: 'Golem, Flesh', nwscript: 'APPEARANCE_TYPE_GOLEM_FLESH', wingTail: 'none' },
  { label: 'Golem, Half-Orc', nwscript: 'APPEARANCE_TYPE_DWARF_HALFORC', wingTail: 'both' },
  { label: 'Golem, Iron', nwscript: 'APPEARANCE_TYPE_GOLEM_IRON', wingTail: 'none' },
  { label: 'Golem, Mithril', nwscript: 'APPEARANCE_TYPE_GOLEM_MITHRAL', wingTail: 'none' },
  { label: 'Golem, Ruby', nwscript: '173', wingTail: 'none' },
  { label: 'Golem, Stone', nwscript: 'APPEARANCE_TYPE_GOLEM_STONE', wingTail: 'none' },
  { label: 'Gorgon', nwscript: 'APPEARANCE_TYPE_GORGON', wingTail: 'none' },
  { label: 'Gray Ooze', nwscript: 'APPEARANCE_TYPE_GRAY_OOZE', wingTail: 'none' },
  { label: 'Grey Render', nwscript: 'APPEARANCE_TYPE_GREY_RENDER', wingTail: 'none' },
  { label: 'Gynosphinx', nwscript: 'APPEARANCE_TYPE_GYNOSPHINX', wingTail: 'none' },
  { label: 'Hagatha', nwscript: '459', wingTail: 'none' },
  { label: 'Halaster', nwscript: '460', wingTail: 'none' },
  { label: 'Half-elf', nwscript: 'APPEARANCE_TYPE_HALF_ELF', wingTail: 'both' },
  { label: 'Half-Elf mounted, female', nwscript: '490', wingTail: 'both' },
  { label: 'Half-Elf mounted, male', nwscript: '491', wingTail: 'both' },
  { label: 'Half-orc', nwscript: 'APPEARANCE_TYPE_HALF_ORC', wingTail: 'both' },
  { label: 'Half-orc mounted, female', nwscript: '492', wingTail: 'both' },
  { label: 'Half-orc mounted, male', nwscript: '493', wingTail: 'both' },
  { label: 'Half-orc, female', nwscript: 'APPEARANCE_TYPE_HALF_ORC_NPC_FEMALE', wingTail: 'none' },
  { label: 'Half-orc, male 1', nwscript: 'APPEARANCE_TYPE_HALF_ORC_NPC_MALE_01', wingTail: 'none' },
  { label: 'Half-orc, male 2', nwscript: 'APPEARANCE_TYPE_HALF_ORC_NPC_MALE_02', wingTail: 'none' },
  { label: 'Halfling', nwscript: 'APPEARANCE_TYPE_HALFLING', wingTail: 'both' },
  { label: 'Halfling mounted, female', nwscript: '488', wingTail: 'both' },
  { label: 'Halfling mounted, male', nwscript: '489', wingTail: 'both' },
  { label: 'Halfling, female', nwscript: 'APPEARANCE_TYPE_HALFLING_NPC_FEMALE', wingTail: 'none' },
  { label: 'Halfling, male', nwscript: 'APPEARANCE_TYPE_HALFLING_NPC_MALE', wingTail: 'none' },
  { label: 'Harat', nwscript: '461', wingTail: 'none' },
  { label: 'Harat, Small', nwscript: '462', wingTail: 'none' },
  { label: 'Harpy', nwscript: 'APPEARANCE_TYPE_HARPY', wingTail: 'none' },
  { label: 'Helmed Horror', nwscript: 'APPEARANCE_TYPE_HELMED_HORROR', wingTail: 'none' },
  { label: 'Heurodis', nwscript: 'APPEARANCE_TYPE_HEURODIS_LICH', wingTail: 'none' },
  { label: 'Hobgoblin', nwscript: 'APPEARANCE_TYPE_HOBGOBLIN_WARRIOR', wingTail: 'none' },
  { label: 'Hobgoblin, Wizard', nwscript: 'APPEARANCE_TYPE_HOBGOBLIN_WIZARD', wingTail: 'none' },
  { label: 'Hook Horror', nwscript: 'APPEARANCE_TYPE_HOOK_HORROR', wingTail: 'none' },
  { label: 'Horse, Black', nwscript: '535', wingTail: 'none' },
  { label: 'Horse, Black, chain barding', nwscript: '540', wingTail: 'none' },
  { label: 'Horse, Black, chain barding, packs', nwscript: '545', wingTail: 'none' },
  { label: 'Horse, Black, leather barding', nwscript: '538', wingTail: 'none' },
  { label: 'Horse, Black, leather barding, packs', nwscript: '543', wingTail: 'none' },
  { label: 'Horse, Black, purple barding', nwscript: '541', wingTail: 'none' },
  { label: 'Horse, Black, purple barding, packs', nwscript: '546', wingTail: 'none' },
  { label: 'Horse, Black, red barding', nwscript: '542', wingTail: 'none' },
  { label: 'Horse, Black, red barding, packs', nwscript: '547', wingTail: 'none' },
  { label: 'Horse, Black, saddle', nwscript: '536', wingTail: 'none' },
  { label: 'Horse, Black, saddle, packs', nwscript: '537', wingTail: 'none' },
  { label: 'Horse, Black, scale mail barding', nwscript: '539', wingTail: 'none' },
  { label: 'Horse, Black, scale mail barding, packs', nwscript: '544', wingTail: 'none' },
  { label: 'Horse, Gunpowder', nwscript: '509', wingTail: 'none' },
  { label: 'Horse, Gunpowder, chain barding', nwscript: '514', wingTail: 'none' },
  { label: 'Horse, Gunpowder, chain barding, packs', nwscript: '519', wingTail: 'none' },
  { label: 'Horse, Gunpowder, leather barding', nwscript: '512', wingTail: 'none' },
  { label: 'Horse, Gunpowder, leather barding, packs', nwscript: '517', wingTail: 'none' },
  { label: 'Horse, Gunpowder, purple barding', nwscript: '515', wingTail: 'none' },
  { label: 'Horse, Gunpowder, purple barding, packs', nwscript: '520', wingTail: 'none' },
  { label: 'Horse, Gunpowder, red barding', nwscript: '516', wingTail: 'none' },
  { label: 'Horse, Gunpowder, red barding, packs', nwscript: '521', wingTail: 'none' },
  { label: 'Horse, Gunpowder, saddle', nwscript: '510', wingTail: 'none' },
  { label: 'Horse, Gunpowder, saddle, packs', nwscript: '511', wingTail: 'none' },
  { label: 'Horse, Gunpowder, scale mail barding', nwscript: '513', wingTail: 'none' },
  { label: 'Horse, Gunpowder, scale mail barding, packs', nwscript: '518', wingTail: 'none' },
  { label: 'Horse, Jousting, Black and white cloth', nwscript: '553', wingTail: 'none' },
  { label: 'Horse, Jousting, Black cloth', nwscript: '559', wingTail: 'none' },
  { label: 'Horse, Jousting, Blue and gold cloth', nwscript: '552', wingTail: 'none' },
  { label: 'Horse, Jousting, Blue and pink cloth', nwscript: '557', wingTail: 'none' },
  { label: 'Horse, Jousting, Cyan and white cloth', nwscript: '560', wingTail: 'none' },
  { label: 'Horse, Jousting, Green cloth', nwscript: '556', wingTail: 'none' },
  { label: 'Horse, Jousting, Purple cloth', nwscript: '551', wingTail: 'none' },
  { label: 'Horse, Jousting, Red and black striped cloth', nwscript: '555', wingTail: 'none' },
  { label: 'Horse, Jousting, Red and gold brick cloth', nwscript: '558', wingTail: 'none' },
  { label: 'Horse, Jousting, Red and yellow cloth', nwscript: '554', wingTail: 'none' },
  { label: 'Horse, Jousting, White cloth', nwscript: '561', wingTail: 'none' },
  { label: 'Horse, Spotted', nwscript: '522', wingTail: 'none' },
  { label: 'Horse, Spotted, chain barding', nwscript: '527', wingTail: 'none' },
  { label: 'Horse, Spotted, chain barding, packs', nwscript: '532', wingTail: 'none' },
  { label: 'Horse, Spotted, leather barding', nwscript: '525', wingTail: 'none' },
  { label: 'Horse, Spotted, leather barding, packs', nwscript: '530', wingTail: 'none' },
  { label: 'Horse, Spotted, purple barding', nwscript: '528', wingTail: 'none' },
  { label: 'Horse, Spotted, purple barding, packs', nwscript: '533', wingTail: 'none' },
  { label: 'Horse, Spotted, red barding', nwscript: '529', wingTail: 'none' },
  { label: 'Horse, Spotted, red barding, packs', nwscript: '534', wingTail: 'none' },
  { label: 'Horse, Spotted, saddle', nwscript: '523', wingTail: 'none' },
  { label: 'Horse, Spotted, saddle, packs', nwscript: '524', wingTail: 'none' },
  { label: 'Horse, Spotted, scale mail barding', nwscript: '526', wingTail: 'none' },
  { label: 'Horse, Spotted, scale mail barding, packs', nwscript: '531', wingTail: 'none' },
  { label: 'Horse, Walnut', nwscript: '496', wingTail: 'none' },
  { label: 'Horse, Walnut, chain barding', nwscript: '501', wingTail: 'none' },
  { label: 'Horse, Walnut, chain barding, packs', nwscript: '506', wingTail: 'none' },
  { label: 'Horse, Walnut, leather barding', nwscript: '499', wingTail: 'none' },
  { label: 'Horse, Walnut, leather barding, packs', nwscript: '504', wingTail: 'none' },
  { label: 'Horse, Walnut, purple barding', nwscript: '502', wingTail: 'none' },
  { label: 'Horse, Walnut, purple barding, packs', nwscript: '507', wingTail: 'none' },
  { label: 'Horse, Walnut, red barding', nwscript: '503', wingTail: 'none' },
  { label: 'Horse, Walnut, red barding, packs', nwscript: '508', wingTail: 'none' },
  { label: 'Horse, Walnut, saddle', nwscript: '497', wingTail: 'none' },
  { label: 'Horse, Walnut, saddle, packs', nwscript: '498', wingTail: 'none' },
  { label: 'Horse, Walnut, scale mail barding', nwscript: '500', wingTail: 'none' },
  { label: 'Horse, Walnut, scale mail barding, packs', nwscript: '505', wingTail: 'none' },
  { label: 'Hound Archon, Male', nwscript: 'APPEARANCE_TYPE_RAKSHASA_WOLF_MALE', wingTail: 'none' },
  { label: 'House Guard', nwscript: 'APPEARANCE_TYPE_HOUSE_GUARD', wingTail: 'none' },
  { label: 'Human', nwscript: 'APPEARANCE_TYPE_HUMAN', wingTail: 'both' },
  { label: 'Human mounted, female', nwscript: '494', wingTail: 'both' },
  { label: 'Human mounted, male', nwscript: '495', wingTail: 'both' },
  { label: 'Human, Female 01', nwscript: 'APPEARANCE_TYPE_HUMAN_NPC_FEMALE_01', wingTail: 'none' },
  { label: 'Human, Female 02', nwscript: 'APPEARANCE_TYPE_HUMAN_NPC_FEMALE_02', wingTail: 'none' },
  { label: 'Human, Female 03', nwscript: 'APPEARANCE_TYPE_HUMAN_NPC_FEMALE_03', wingTail: 'none' },
  { label: 'Human, Female 04', nwscript: 'APPEARANCE_TYPE_HUMAN_NPC_FEMALE_04', wingTail: 'none' },
  { label: 'Human, Female 05', nwscript: 'APPEARANCE_TYPE_HUMAN_NPC_FEMALE_05', wingTail: 'none' },
  { label: 'Human, Female 06', nwscript: 'APPEARANCE_TYPE_HUMAN_NPC_FEMALE_06', wingTail: 'none' },
  { label: 'Human, Female 07', nwscript: 'APPEARANCE_TYPE_HUMAN_NPC_FEMALE_07', wingTail: 'none' },
  { label: 'Human, Female 08', nwscript: 'APPEARANCE_TYPE_HUMAN_NPC_FEMALE_08', wingTail: 'none' },
  { label: 'Human, Female 09', nwscript: 'APPEARANCE_TYPE_HUMAN_NPC_FEMALE_09', wingTail: 'none' },
  { label: 'Human, Female 10', nwscript: 'APPEARANCE_TYPE_HUMAN_NPC_FEMALE_10', wingTail: 'none' },
  { label: 'Human, Female 11', nwscript: 'APPEARANCE_TYPE_HUMAN_NPC_FEMALE_11', wingTail: 'none' },
  { label: 'Human, Female 12', nwscript: 'APPEARANCE_TYPE_HUMAN_NPC_FEMALE_12', wingTail: 'none' },
  { label: 'Human, Male 01 ', nwscript: 'APPEARANCE_TYPE_HUMAN_NPC_MALE_01', wingTail: 'none' },
  { label: 'Human, Male 02', nwscript: 'APPEARANCE_TYPE_HUMAN_NPC_MALE_02', wingTail: 'none' },
  { label: 'Human, Male 03', nwscript: 'APPEARANCE_TYPE_HUMAN_NPC_MALE_03', wingTail: 'none' },
  { label: 'Human, Male 04', nwscript: 'APPEARANCE_TYPE_HUMAN_NPC_MALE_04', wingTail: 'none' },
  { label: 'Human, Male 05', nwscript: 'APPEARANCE_TYPE_HUMAN_NPC_MALE_05', wingTail: 'none' },
  { label: 'Human, Male 06', nwscript: 'APPEARANCE_TYPE_HUMAN_NPC_MALE_06', wingTail: 'none' },
  { label: 'Human, Male 07', nwscript: 'APPEARANCE_TYPE_HUMAN_NPC_MALE_07', wingTail: 'none' },
  { label: 'Human, Male 08', nwscript: 'APPEARANCE_TYPE_HUMAN_NPC_MALE_08', wingTail: 'none' },
  { label: 'Human, Male 09', nwscript: 'APPEARANCE_TYPE_HUMAN_NPC_MALE_09', wingTail: 'none' },
  { label: 'Human, Male 10', nwscript: 'APPEARANCE_TYPE_HUMAN_NPC_MALE_10', wingTail: 'none' },
  { label: 'Human, Male 11', nwscript: 'APPEARANCE_TYPE_HUMAN_NPC_MALE_11', wingTail: 'none' },
  { label: 'Human, Male 12', nwscript: 'APPEARANCE_TYPE_HUMAN_NPC_MALE_12', wingTail: 'none' },
  { label: 'Human, Male 13', nwscript: 'APPEARANCE_TYPE_HUMAN_NPC_MALE_13', wingTail: 'none' },
  { label: 'Human, Male 14', nwscript: 'APPEARANCE_TYPE_HUMAN_NPC_MALE_14', wingTail: 'none' },
  { label: 'Human, Male 15', nwscript: 'APPEARANCE_TYPE_HUMAN_NPC_MALE_15', wingTail: 'none' },
  { label: 'Human, Male 16', nwscript: 'APPEARANCE_TYPE_HUMAN_NPC_MALE_16', wingTail: 'none' },
  { label: 'Human, Male 17', nwscript: 'APPEARANCE_TYPE_HUMAN_NPC_MALE_17', wingTail: 'none' },
  { label: 'Human, Male 18', nwscript: 'APPEARANCE_TYPE_HUMAN_NPC_MALE_18', wingTail: 'none' },
  { label: 'Imp', nwscript: 'APPEARANCE_TYPE_IMP', wingTail: 'none' },
  { label: 'Innkeeper', nwscript: 'APPEARANCE_TYPE_INN_KEEPER', wingTail: 'none' },
  { label: 'Intellect Devourer', nwscript: 'APPEARANCE_TYPE_INTELLECT_DEVOURER', wingTail: 'none' },
  { label: 'Intellect Devourer, Skeletal', nwscript: 'APPEARANCE_TYPE_SKELETAL_DEVOURER', wingTail: 'none' },
  { label: 'Intellect Devourer, War', nwscript: 'APPEARANCE_TYPE_WAR_DEVOURER', wingTail: 'none' },
  { label: 'Invisible Stalker', nwscript: 'APPEARANCE_TYPE_INVISIBLE_STALKER', wingTail: 'none' },
  { label: 'Kobold A', nwscript: 'APPEARANCE_TYPE_KOBOLD_A', wingTail: 'wing' },
  { label: 'Kobold B', nwscript: 'APPEARANCE_TYPE_KOBOLD_B', wingTail: 'wing' },
  { label: 'Kobold, Footpad', nwscript: 'APPEARANCE_TYPE_KOBOLD_CHIEF_B', wingTail: 'wing' },
  { label: 'Kobold, Healer', nwscript: 'APPEARANCE_TYPE_KOBOLD_SHAMAN_B', wingTail: 'wing' },
  { label: 'Kobold, Shaman', nwscript: 'APPEARANCE_TYPE_KOBOLD_SHAMAN_A', wingTail: 'wing' },
  { label: 'Kobold, Thug', nwscript: 'APPEARANCE_TYPE_KOBOLD_CHIEF_A', wingTail: 'wing' },
  { label: 'Lantern Archon', nwscript: 'APPEARANCE_TYPE_LANTERN_ARCHON', wingTail: 'none' },
  { label: 'Lich', nwscript: 'APPEARANCE_TYPE_LICH', wingTail: 'none' },
  { label: 'Lizardfolk A', nwscript: 'APPEARANCE_TYPE_LIZARDFOLK_A', wingTail: 'tail' },
  { label: 'Lizardfolk B', nwscript: 'APPEARANCE_TYPE_LIZARDFOLK_B', wingTail: 'tail' },
  { label: 'Lizardfolk, Shaman A', nwscript: 'APPEARANCE_TYPE_LIZARDFOLK_SHAMAN_A', wingTail: 'tail' },
  { label: 'Lizardfolk, Shaman B', nwscript: 'APPEARANCE_TYPE_LIZARDFOLK_SHAMAN_B', wingTail: 'tail' },
  { label: 'Lizardfolk, Warrior A', nwscript: 'APPEARANCE_TYPE_LIZARDFOLK_WARRIOR_A', wingTail: 'tail' },
  { label: 'Lizardfolk, Warrior B', nwscript: 'APPEARANCE_TYPE_LIZARDFOLK_WARRIOR_B', wingTail: 'tail' },
  { label: 'Lord Antoine', nwscript: '417', wingTail: 'none' },
  { label: 'Luskan Guard', nwscript: 'APPEARANCE_TYPE_LUSKAN_GUARD', wingTail: 'none' },
  { label: 'Maggris', nwscript: '463', wingTail: 'none' },
  { label: 'Magic sparks, blue', nwscript: 'APPEARANCE_TYPE_OBJECT_BLUE', wingTail: 'none' },
  { label: 'Magic sparks, cyan', nwscript: 'APPEARANCE_TYPE_OBJECT_CYAN', wingTail: 'none' },
  { label: 'Magic sparks, green', nwscript: 'APPEARANCE_TYPE_OBJECT_GREEN', wingTail: 'none' },
  { label: 'Magic sparks, orange', nwscript: 'APPEARANCE_TYPE_OBJECT_ORANGE', wingTail: 'none' },
  { label: 'Magic sparks, purple', nwscript: 'APPEARANCE_TYPE_OBJECT_PURPLE', wingTail: 'none' },
  { label: 'Magic sparks, red', nwscript: 'APPEARANCE_TYPE_OBJECT_RED', wingTail: 'none' },
  { label: 'Magic sparks, white', nwscript: 'APPEARANCE_TYPE_OBJECT_WHITE', wingTail: 'none' },
  { label: 'Magic sparks, yellow', nwscript: 'APPEARANCE_TYPE_OBJECT_YELLOW', wingTail: 'none' },
  { label: 'Male 1', nwscript: 'APPEARANCE_TYPE_MALE_01', wingTail: 'none' },
  { label: 'Male 2', nwscript: 'APPEARANCE_TYPE_MALE_02', wingTail: 'none' },
  { label: 'Male 3', nwscript: 'APPEARANCE_TYPE_MALE_03', wingTail: 'none' },
  { label: 'Male 4', nwscript: 'APPEARANCE_TYPE_MALE_04', wingTail: 'none' },
  { label: 'Male 5', nwscript: 'APPEARANCE_TYPE_MALE_05', wingTail: 'none' },
  { label: 'Manticore', nwscript: 'APPEARANCE_TYPE_MANTICORE', wingTail: 'none' },
  { label: 'Masterius', nwscript: '464', wingTail: 'none' },
  { label: 'Masterius, Full Power', nwscript: '465', wingTail: 'none' },
  { label: 'Medusa', nwscript: 'APPEARANCE_TYPE_MEDUSA', wingTail: 'none' },
  { label: 'Mephistopheles', nwscript: 'APPEARANCE_TYPE_MEPHISTO_NORM', wingTail: 'none' },
  { label: 'Mephistopheles, Large', nwscript: 'APPEARANCE_TYPE_MEPHISTO_BIG', wingTail: 'none' },
  { label: 'Mephit, Air', nwscript: 'APPEARANCE_TYPE_MEPHIT_AIR', wingTail: 'none' },
  { label: 'Mephit, Dust', nwscript: 'APPEARANCE_TYPE_MEPHIT_DUST', wingTail: 'none' },
  { label: 'Mephit, Earth', nwscript: 'APPEARANCE_TYPE_MEPHIT_EARTH', wingTail: 'none' },
  { label: 'Mephit, Fire', nwscript: 'APPEARANCE_TYPE_MEPHIT_FIRE', wingTail: 'none' },
  { label: 'Mephit, Ice', nwscript: 'APPEARANCE_TYPE_MEPHIT_ICE', wingTail: 'none' },
  { label: 'Mephit, Magma', nwscript: 'APPEARANCE_TYPE_MEPHIT_MAGMA', wingTail: 'none' },
  { label: 'Mephit, Ooze', nwscript: 'APPEARANCE_TYPE_MEPHIT_OOZE', wingTail: 'none' },
  { label: 'Mephit, Salt', nwscript: 'APPEARANCE_TYPE_MEPHIT_SALT', wingTail: 'none' },
  { label: 'Mephit, Steam', nwscript: 'APPEARANCE_TYPE_MEPHIT_STEAM', wingTail: 'none' },
  { label: 'Mephit, Water', nwscript: 'APPEARANCE_TYPE_MEPHIT_WATER', wingTail: 'none' },
  { label: 'Mimic', nwscript: 'APPEARANCE_TYPE_ANIMATED_CHEST', wingTail: 'none' },
  { label: 'Mindflayer', nwscript: 'APPEARANCE_TYPE_MINDFLAYER', wingTail: 'none' },
  { label: 'Mindflayer, Alhoon', nwscript: 'APPEARANCE_TYPE_MINDFLAYER_ALHOON', wingTail: 'none' },
  { label: 'Mindflayer, Master', nwscript: 'APPEARANCE_TYPE_MINDFLAYER_2', wingTail: 'none' },
  { label: 'Minogon', nwscript: 'APPEARANCE_TYPE_MINOGON', wingTail: 'none' },
  { label: 'Minotaur', nwscript: 'APPEARANCE_TYPE_MINOTAUR', wingTail: 'none' },
  { label: 'Minotaur, Chieftain', nwscript: 'APPEARANCE_TYPE_MINOTAUR_CHIEFTAIN', wingTail: 'none' },
  { label: 'Minotaur, Shaman', nwscript: 'APPEARANCE_TYPE_MINOTAUR_SHAMAN', wingTail: 'none' },
  { label: 'Mohrg', nwscript: 'APPEARANCE_TYPE_MOHRG', wingTail: 'none' },
  { label: 'Mummy, Common', nwscript: 'APPEARANCE_TYPE_MUMMY_COMMON', wingTail: 'none' },
  { label: 'Mummy, Greater', nwscript: 'APPEARANCE_TYPE_MUMMY_GREATER', wingTail: 'none' },
  { label: 'Mummy, Warrior 1', nwscript: 'APPEARANCE_TYPE_MUMMY_WARRIOR', wingTail: 'none' },
  { label: 'Mummy, Warrior 2', nwscript: 'APPEARANCE_TYPE_MUMMY_FIGHTER_2', wingTail: 'none' },
  { label: 'Neverwinter Militia Member', nwscript: 'APPEARANCE_TYPE_NW_MILITIA_MEMBER', wingTail: 'none' },
  { label: 'Nightmare', nwscript: '550', wingTail: 'none' },
  { label: 'Nightmare, barding', nwscript: '548', wingTail: 'none' },
  { label: 'Nightmare, saddle', nwscript: '549', wingTail: 'none' },
  { label: 'NWN Nasher', nwscript: 'APPEARANCE_TYPE_NWN_NASHER', wingTail: 'none' },
  { label: 'NWN Sedos', nwscript: 'APPEARANCE_TYPE_NWN_SEDOS', wingTail: 'none' },
  { label: 'NWN, Aarin', nwscript: 'APPEARANCE_TYPE_NWN_AARIN', wingTail: 'none' },
  { label: 'NWN, Aribeth 1', nwscript: 'APPEARANCE_TYPE_ARIBETH', wingTail: 'none' },
  { label: 'NWN, Aribeth 2', nwscript: 'APPEARANCE_TYPE_NWN_ARIBETH_EVIL', wingTail: 'none' },
  { label: 'NWN, Haedraline', nwscript: 'APPEARANCE_TYPE_NWN_HAEDRALINE', wingTail: 'none' },
  { label: 'NWN, Maugrim', nwscript: 'APPEARANCE_TYPE_NWN_MAUGRIM', wingTail: 'none' },
  { label: 'NWN, Morag', nwscript: 'APPEARANCE_TYPE_NWN_MORAG', wingTail: 'none' },
  { label: 'Nymph', nwscript: 'APPEARANCE_TYPE_NYMPH', wingTail: 'none' },
  { label: 'Ochre Jelly, Large', nwscript: 'APPEARANCE_TYPE_OCHRE_JELLY_LARGE', wingTail: 'none' },
  { label: 'Ochre Jelly, Medium', nwscript: 'APPEARANCE_TYPE_OCHRE_JELLY_MEDIUM', wingTail: 'none' },
  { label: 'Ochre Jelly, Small', nwscript: 'APPEARANCE_TYPE_OCHRE_JELLY_SMALL', wingTail: 'none' },
  { label: 'Ogre A', nwscript: 'APPEARANCE_TYPE_OGRE', wingTail: 'none' },
  { label: 'Ogre B', nwscript: 'APPEARANCE_TYPE_OGREB', wingTail: 'none' },
  { label: 'Ogre, Chieftain A', nwscript: 'APPEARANCE_TYPE_OGRE_CHIEFTAIN', wingTail: 'none' },
  { label: 'Ogre, Chieftain B', nwscript: 'APPEARANCE_TYPE_OGRE_CHIEFTAINB', wingTail: 'none' },
  { label: 'Ogre, Elite', nwscript: '75', wingTail: 'none' },
  { label: 'Ogre, Mage A', nwscript: 'APPEARANCE_TYPE_OGRE_MAGE', wingTail: 'none' },
  { label: 'Ogre, Mage B', nwscript: 'APPEARANCE_TYPE_OGRE_MAGEB', wingTail: 'none' },
  { label: 'Old Man', nwscript: 'APPEARANCE_TYPE_OLD_MAN', wingTail: 'none' },
  { label: 'Old Woman', nwscript: 'APPEARANCE_TYPE_OLD_WOMAN', wingTail: 'none' },
  { label: 'Orc A', nwscript: 'APPEARANCE_TYPE_ORC_A', wingTail: 'none' },
  { label: 'Orc B', nwscript: 'APPEARANCE_TYPE_ORC_B', wingTail: 'none' },
  { label: 'Orc, Chieftain A', nwscript: 'APPEARANCE_TYPE_ORC_CHIEFTAIN_A', wingTail: 'none' },
  { label: 'Orc, Chieftain B', nwscript: 'APPEARANCE_TYPE_ORC_CHIEFTAIN_B', wingTail: 'none' },
  { label: 'Orc, Shaman A', nwscript: 'APPEARANCE_TYPE_ORC_SHAMAN_A', wingTail: 'none' },
  { label: 'Orc, Shaman B', nwscript: 'APPEARANCE_TYPE_ORC_SHAMAN_B', wingTail: 'none' },
  { label: 'Ox', nwscript: 'APPEARANCE_TYPE_OX', wingTail: 'none' },
  { label: 'Parrot', nwscript: 'APPEARANCE_TYPE_PARROT', wingTail: 'none' },
  { label: 'Penguin', nwscript: 'APPEARANCE_TYPE_PENGUIN', wingTail: 'none' },
  { label: 'Plague Victim', nwscript: 'APPEARANCE_TYPE_PLAGUE_VICTIM', wingTail: 'none' },
  { label: 'Prostitute 1', nwscript: 'APPEARANCE_TYPE_PROSTITUTE_01', wingTail: 'none' },
  { label: 'Prostitute 2', nwscript: 'APPEARANCE_TYPE_PROSTITUTE_02', wingTail: 'none' },
  { label: 'Pseudodragon', nwscript: 'APPEARANCE_TYPE_PSEUDODRAGON', wingTail: 'none' },
  { label: 'Purple Dragon Knight Archer, Female', nwscript: '395', wingTail: 'none' },
  { label: 'Purple Dragon Knight Archer, Male', nwscript: '397', wingTail: 'none' },
  { label: 'Purple Dragon Knight Blade, Female', nwscript: '399', wingTail: 'none' },
  { label: 'Purple Dragon Knight Blade, Male', nwscript: '400', wingTail: 'none' },
  { label: 'Quasit', nwscript: 'APPEARANCE_TYPE_QUASIT', wingTail: 'none' },
  { label: 'Rakshasa, Female', nwscript: 'APPEARANCE_TYPE_RAKSHASA_TIGER_FEMALE', wingTail: 'none' },
  { label: 'Rakshasa, Male', nwscript: 'APPEARANCE_TYPE_RAKSHASA_TIGER_MALE', wingTail: 'none' },
  { label: 'Rat', nwscript: 'APPEARANCE_TYPE_RAT', wingTail: 'none' },
  { label: 'Rat, Dire', nwscript: 'APPEARANCE_TYPE_RAT_DIRE', wingTail: 'none' },
  { label: 'Raven', nwscript: 'APPEARANCE_TYPE_RAVEN', wingTail: 'none' },
  { label: 'Sahuagin', nwscript: 'APPEARANCE_TYPE_SAHUAGIN', wingTail: 'none' },
  { label: 'Sahuagin Cleric', nwscript: 'APPEARANCE_TYPE_SAHUAGIN_CLERIC', wingTail: 'none' },
  { label: 'Sahuagin Leader', nwscript: 'APPEARANCE_TYPE_SAHUAGIN_LEADER', wingTail: 'none' },
  { label: 'Satyr', nwscript: '143', wingTail: 'none' },
  { label: 'Satyr, Archer', nwscript: '32', wingTail: 'none' },
  { label: 'Satyr, Warrior', nwscript: '33', wingTail: 'none' },
  { label: 'Sea Hag', nwscript: 'APPEARANCE_TYPE_SEA_HAG', wingTail: 'none' },
  { label: 'Seagull, flying', nwscript: 'APPEARANCE_TYPE_SEAGULL_FLYING', wingTail: 'none' },
  { label: 'Seagull, walking', nwscript: 'APPEARANCE_TYPE_SEAGULL_WALKING', wingTail: 'none' },
  { label: 'Shadow', nwscript: 'APPEARANCE_TYPE_SHADOW', wingTail: 'none' },
  { label: 'Shadow Fiend', nwscript: 'APPEARANCE_TYPE_SHADOW_FIEND', wingTail: 'none' },
  { label: 'Shark, Goblin', nwscript: 'APPEARANCE_TYPE_SHARK_GOBLIN', wingTail: 'none' },
  { label: 'Shark, Hammerhead', nwscript: 'APPEARANCE_TYPE_SHARK_HAMMERHEAD', wingTail: 'none' },
  { label: 'Shark, Mako', nwscript: 'APPEARANCE_TYPE_SHARK_MAKO', wingTail: 'none' },
  { label: 'Shield Guardian', nwscript: 'APPEARANCE_TYPE_SHIELD_GUARDIAN', wingTail: 'none' },
  { label: 'Shopkeeper', nwscript: 'APPEARANCE_TYPE_SHOP_KEEPER', wingTail: 'none' },
  { label: 'Skeleton, Chieftain', nwscript: 'APPEARANCE_TYPE_SKELETON_CHIEFTAIN', wingTail: 'none' },
  { label: 'Skeleton, Common', nwscript: 'APPEARANCE_TYPE_SKELETON_COMMON', wingTail: 'none' },
  { label: 'Skeleton, Mage', nwscript: 'APPEARANCE_TYPE_SKELETON_MAGE', wingTail: 'none' },
  { label: 'Skeleton, Priest', nwscript: 'APPEARANCE_TYPE_SKELETON_PRIEST', wingTail: 'none' },
  { label: 'Skeleton, Warrior', nwscript: 'APPEARANCE_TYPE_SKELETON_WARRIOR', wingTail: 'none' },
  { label: 'Skeleton, Warrior 1', nwscript: 'APPEARANCE_TYPE_SKELETON_WARRIOR_1', wingTail: 'none' },
  { label: 'Skeleton, Warrior 2', nwscript: 'APPEARANCE_TYPE_SKELETON_WARRIOR_2', wingTail: 'none' },
  { label: 'Slaad, Black', nwscript: 'APPEARANCE_TYPE_SLAAD_BLACK', wingTail: 'none' },
  { label: 'Slaad, Blue', nwscript: 'APPEARANCE_TYPE_SLAAD_BLUE', wingTail: 'none' },
  { label: 'Slaad, Death', nwscript: 'APPEARANCE_TYPE_SLAAD_DEATH', wingTail: 'none' },
  { label: 'Slaad, Gray', nwscript: 'APPEARANCE_TYPE_SLAAD_GRAY', wingTail: 'none' },
  { label: 'Slaad, Green', nwscript: 'APPEARANCE_TYPE_SLAAD_GREEN', wingTail: 'none' },
  { label: 'Slaad, Red', nwscript: 'APPEARANCE_TYPE_SLAAD_RED', wingTail: 'none' },
  { label: 'Slaad, White', nwscript: 'APPEARANCE_TYPE_SLAAD_WHITE', wingTail: 'none' },
  { label: 'Snake, Black Cobra', nwscript: '178', wingTail: 'none' },
  { label: 'Snake, Cobra', nwscript: '183', wingTail: 'none' },
  { label: 'Snake, Gold Cobra', nwscript: '194', wingTail: 'none' },
  { label: 'Spectre', nwscript: 'APPEARANCE_TYPE_SPECTRE', wingTail: 'none' },
  { label: 'Sphinx', nwscript: 'APPEARANCE_TYPE_SPHINX', wingTail: 'none' },
  { label: 'Spider, Dire', nwscript: 'APPEARANCE_TYPE_SPIDER_DIRE', wingTail: 'none' },
  { label: 'Spider, Giant', nwscript: 'APPEARANCE_TYPE_SPIDER_GIANT', wingTail: 'none' },
  { label: 'Spider, Phase', nwscript: 'APPEARANCE_TYPE_SPIDER_PHASE', wingTail: 'none' },
  { label: 'Spider, Sword', nwscript: 'APPEARANCE_TYPE_SPIDER_SWORD', wingTail: 'none' },
  { label: 'Spider, Wraith', nwscript: 'APPEARANCE_TYPE_SPIDER_WRAITH', wingTail: 'none' },
  { label: 'Stinger', nwscript: 'APPEARANCE_TYPE_STINGER', wingTail: 'none' },
  { label: 'Stinger Chieftain', nwscript: 'APPEARANCE_TYPE_STINGER_CHIEFTAIN', wingTail: 'none' },
  { label: 'Stinger Mage', nwscript: 'APPEARANCE_TYPE_STINGER_MAGE', wingTail: 'none' },
  { label: 'Stinger Warrior', nwscript: 'APPEARANCE_TYPE_STINGER_WARRIOR', wingTail: 'none' },
  { label: 'Succubus', nwscript: 'APPEARANCE_TYPE_SUCCUBUS', wingTail: 'wing' },
  { label: 'Svirfneblin, Female', nwscript: 'APPEARANCE_TYPE_SVIRF_FEMALE', wingTail: 'none' },
  { label: 'Svirfneblin, Male', nwscript: 'APPEARANCE_TYPE_SVIRF_MALE', wingTail: 'none' },
  { label: 'Table', nwscript: 'APPEARANCE_TYPE_OBJECT_TABLE', wingTail: 'none' },
  { label: 'Troglodyte', nwscript: 'APPEARANCE_TYPE_TROGLODYTE', wingTail: 'none' },
  { label: 'Troglodyte (green)', nwscript: '870', wingTail: 'none' },
  { label: 'Troglodyte (red)', nwscript: '869', wingTail: 'none' },
  { label: 'Troglodyte Cleric', nwscript: 'APPEARANCE_TYPE_TROGLODYTE_CLERIC', wingTail: 'none' },
  { label: 'Troglodyte Warrior', nwscript: 'APPEARANCE_TYPE_TROGLODYTE_WARRIOR', wingTail: 'none' },
  { label: 'Troll', nwscript: 'APPEARANCE_TYPE_TROLL', wingTail: 'none' },
  { label: 'Troll, Chieftain', nwscript: 'APPEARANCE_TYPE_TROLL_CHIEFTAIN', wingTail: 'none' },
  { label: 'Troll, Shaman', nwscript: 'APPEARANCE_TYPE_TROLL_SHAMAN', wingTail: 'none' },
  { label: 'Umber Hulk', nwscript: 'APPEARANCE_TYPE_UMBERHULK', wingTail: 'none' },
  { label: 'Uthgard Elk Tribe', nwscript: 'APPEARANCE_TYPE_UTHGARD_ELK_TRIBE', wingTail: 'none' },
  { label: 'Uthgard Tiger Tribe', nwscript: 'APPEARANCE_TYPE_UTHGARD_TIGER_TRIBE', wingTail: 'none' },
  { label: 'Vampire, Female', nwscript: 'APPEARANCE_TYPE_VAMPIRE_FEMALE', wingTail: 'none' },
  { label: 'Vampire, Male', nwscript: 'APPEARANCE_TYPE_VAMPIRE_MALE', wingTail: 'none' },
  { label: 'Vrock', nwscript: 'APPEARANCE_TYPE_VROCK', wingTail: 'none' },
  { label: 'Waitress', nwscript: 'APPEARANCE_TYPE_WAITRESS', wingTail: 'none' },
  { label: 'Wereboar', nwscript: '467', wingTail: 'none' },
  { label: 'Werecat', nwscript: 'APPEARANCE_TYPE_WERECAT', wingTail: 'none' },
  { label: 'Wererat', nwscript: 'APPEARANCE_TYPE_WERERAT', wingTail: 'none' },
  { label: 'Werewolf', nwscript: 'APPEARANCE_TYPE_WEREWOLF', wingTail: 'none' },
  { label: 'Wight', nwscript: 'APPEARANCE_TYPE_WIGHT', wingTail: 'none' },
  { label: 'Will-O-Wisp', nwscript: 'APPEARANCE_TYPE_WILL_O_WISP', wingTail: 'none' },
  { label: 'Witch King, Disguised', nwscript: '466', wingTail: 'none' },
  { label: 'Wraith', nwscript: 'APPEARANCE_TYPE_WRAITH', wingTail: 'none' },
  { label: 'Wyrmling, Black', nwscript: 'APPEARANCE_TYPE_WYRMLING_BLACK', wingTail: 'none' },
  { label: 'Wyrmling, Blue', nwscript: 'APPEARANCE_TYPE_WYRMLING_BLUE', wingTail: 'none' },
  { label: 'Wyrmling, Brass', nwscript: 'APPEARANCE_TYPE_WYRMLING_BRASS', wingTail: 'none' },
  { label: 'Wyrmling, Bronze', nwscript: 'APPEARANCE_TYPE_WYRMLING_BRONZE', wingTail: 'none' },
  { label: 'Wyrmling, Copper', nwscript: 'APPEARANCE_TYPE_WYRMLING_COPPER', wingTail: 'none' },
  { label: 'Wyrmling, Gold', nwscript: 'APPEARANCE_TYPE_WYRMLING_GOLD', wingTail: 'none' },
  { label: 'Wyrmling, Green', nwscript: 'APPEARANCE_TYPE_WYRMLING_GREEN', wingTail: 'none' },
  { label: 'Wyrmling, Red', nwscript: 'APPEARANCE_TYPE_WYRMLING_RED', wingTail: 'none' },
  { label: 'Wyrmling, Silver', nwscript: 'APPEARANCE_TYPE_WYRMLING_SILVER', wingTail: 'none' },
  { label: 'Wyrmling, White', nwscript: 'APPEARANCE_TYPE_WYRMLING_WHITE', wingTail: 'none' },
  { label: 'Wyvern, Adult', nwscript: '455', wingTail: 'none' },
  { label: 'Wyvern, Great', nwscript: '456', wingTail: 'none' },
  { label: 'Wyvern, Juvenile', nwscript: '457', wingTail: 'none' },
  { label: 'Wyvern, Young', nwscript: '458', wingTail: 'none' },
  { label: 'Yuan-Ti, Invoker', nwscript: 'APPEARANCE_TYPE_YUAN_TI_CHIEFTEN', wingTail: 'none' },
  { label: 'Yuan-Ti, Necromancer', nwscript: 'APPEARANCE_TYPE_YUAN_TI_WIZARD', wingTail: 'none' },
  { label: 'Yuan-Ti, Priest', nwscript: 'APPEARANCE_TYPE_YUAN_TI', wingTail: 'none' },
  { label: 'Zombie, Common', nwscript: 'APPEARANCE_TYPE_ZOMBIE', wingTail: 'none' },
  { label: 'Zombie, Rotting', nwscript: 'APPEARANCE_TYPE_ZOMBIE_ROTTING', wingTail: 'none' },
  { label: 'Zombie, Tyrant Fog', nwscript: 'APPEARANCE_TYPE_ZOMBIE_TYRANT_FOG', wingTail: 'none' },
  { label: 'Zombie, Warrior 1', nwscript: 'APPEARANCE_TYPE_ZOMBIE_WARRIOR_1', wingTail: 'none' },
  { label: 'Zombie, Warrior 2', nwscript: 'APPEARANCE_TYPE_ZOMBIE_WARRIOR_2', wingTail: 'none' },
];

