/**
 * VFX Constants
 * Extracted from constants.pas
 */

// VFX_DURATION: 381 entries
export const VFX_DURATION = [
  { label: 'No visual effect', nwscript: 'VFX_NONE' },
  { label: 'Duration: anti-light 10', nwscript: 'VFX_DUR_ANTI_LIGHT_10' },
  { label: 'Duration: arrow, black 1', nwscript: '654' },
  { label: 'Duration: arrow, black 2', nwscript: '655' },
  { label: 'Duration: arrow, black 3', nwscript: '656' },
  { label: 'Duration: arrow, black 4', nwscript: '657' },
  { label: 'Duration: arrow, black 5', nwscript: '658' },
  { label: 'Duration: arrow, blue 1', nwscript: '659' },
  { label: 'Duration: arrow, blue 2', nwscript: '660' },
  { label: 'Duration: arrow, blue 3', nwscript: '661' },
  { label: 'Duration: arrow, blue 4', nwscript: '662' },
  { label: 'Duration: arrow, blue 5', nwscript: '663' },
  { label: 'Duration: arrow, red 1', nwscript: '664' },
  { label: 'Duration: arrow, red 2', nwscript: '665' },
  { label: 'Duration: arrow, red 3', nwscript: '666' },
  { label: 'Duration: arrow, white 1', nwscript: '646' },
  { label: 'Duration: arrow, white 2', nwscript: '647' },
  { label: 'Duration: arrow, white 3', nwscript: '648' },
  { label: 'Duration: arrow, white 4', nwscript: '649' },
  { label: 'Duration: arrow, white 5', nwscript: '650' },
  { label: 'Duration: arrow, white 6', nwscript: '651' },
  { label: 'Duration: arrow, white 7', nwscript: '652' },
  { label: 'Duration: arrow, white 8', nwscript: '653' },
  { label: 'Duration: arrow, yellow 1', nwscript: '667' },
  { label: 'Duration: arrow, yellow 2', nwscript: '668' },
  { label: 'Duration: arrow, yellow 3', nwscript: '669' },
  { label: 'Duration: arrow in back', nwscript: 'VFX_DUR_ARROW_IN_BACK' },
  { label: 'Duration: arrow in chest, left', nwscript: 'VFX_DUR_ARROW_IN_CHEST_LEFT' },
  { label: 'Duration: arrow in chest, right', nwscript: 'VFX_DUR_ARROW_IN_CHEST_RIGHT' },
  { label: 'Duration: arrow in face', nwscript: 'VFX_DUR_ARROW_IN_FACE' },
  { label: 'Duration: arrow in head', nwscript: 'VFX_DUR_ARROW_IN_HEAD' },
  { label: 'Duration: arrow in sternum', nwscript: 'VFX_DUR_ARROW_IN_STERNUM' },
  { label: 'Duration: arrow in temples', nwscript: 'VFX_DUR_ARROW_IN_TEMPLES' },
  { label: 'Duration: aura blue', nwscript: 'VFX_DUR_AURA_BLUE' },
  { label: 'Duration: aura blue, dark', nwscript: 'VFX_DUR_AURA_BLUE_DARK' },
  { label: 'Duration: aura blue, light', nwscript: 'VFX_DUR_AURA_BLUE_LIGHT' },
  { label: 'Duration: aura brown', nwscript: 'VFX_DUR_AURA_BROWN' },
  { label: 'Duration: aura cold', nwscript: 'VFX_DUR_AURA_COLD' },
  { label: 'Duration: aura cyan', nwscript: 'VFX_DUR_AURA_CYAN' },
  { label: 'Duration: aura disease', nwscript: 'VFX_DUR_AURA_DISEASE' },
  { label: 'Duration: aura dragon fear', nwscript: 'VFX_DUR_AURA_DRAGON_FEAR' },
  { label: 'Duration: aura fear', nwscript: 'VFX_IMP_AURA_FEAR' },
  { label: 'Duration: aura fire', nwscript: 'VFX_DUR_AURA_FIRE' },
  { label: 'Duration: aura green', nwscript: 'VFX_DUR_AURA_GREEN' },
  { label: 'Duration: aura green, dark', nwscript: 'VFX_DUR_AURA_GREEN_DARK' },
  { label: 'Duration: aura green, light', nwscript: 'VFX_DUR_AURA_GREEN_LIGHT' },
  { label: 'Duration: aura holy', nwscript: 'VFX_IMP_AURA_HOLY' },
  { label: 'Duration: aura magenta', nwscript: 'VFX_DUR_AURA_MAGENTA' },
  { label: 'Duration: aura negative energy', nwscript: 'VFX_IMP_AURA_NEGATIVE_ENERGY' },
  { label: 'Duration: aura odd', nwscript: 'VFX_DUR_AURA_ODD' },
  { label: 'Duration: aura orange', nwscript: 'VFX_DUR_AURA_ORANGE' },
  { label: 'Duration: aura poison', nwscript: 'VFX_DUR_AURA_POISON' },
  { label: 'Duration: aura pulse blue/black', nwscript: 'VFX_DUR_AURA_PULSE_BLUE_BLACK' },
  { label: 'Duration: aura pulse blue/green', nwscript: 'VFX_DUR_AURA_PULSE_BLUE_GREEN' },
  { label: 'Duration: aura pulse blue/white', nwscript: 'VFX_DUR_AURA_PULSE_BLUE_WHITE' },
  { label: 'Duration: aura pulse blue/yellow', nwscript: 'VFX_DUR_AURA_PULSE_BLUE_YELLOW' },
  { label: 'Duration: aura pulse brown/black', nwscript: 'VFX_DUR_AURA_PULSE_BROWN_BLACK' },
  { label: 'Duration: aura pulse brown/white', nwscript: 'VFX_DUR_AURA_PULSE_BROWN_WHITE' },
  { label: 'Duration: aura pulse cyan/black', nwscript: 'VFX_DUR_AURA_PULSE_CYAN_BLACK' },
  { label: 'Duration: aura pulse cyan/blue', nwscript: 'VFX_DUR_AURA_PULSE_CYAN_BLUE' },
  { label: 'Duration: aura pulse cyan/green', nwscript: 'VFX_DUR_AURA_PULSE_CYAN_GREEN' },
  { label: 'Duration: aura pulse cyan/red', nwscript: 'VFX_DUR_AURA_PULSE_CYAN_RED' },
  { label: 'Duration: aura pulse cyan/white', nwscript: 'VFX_DUR_AURA_PULSE_CYAN_WHITE' },
  { label: 'Duration: aura pulse cyan/yellow', nwscript: 'VFX_DUR_AURA_PULSE_CYAN_YELLOW' },
  { label: 'Duration: aura pulse green/black', nwscript: 'VFX_DUR_AURA_PULSE_GREEN_BLACK' },
  { label: 'Duration: aura pulse green/white', nwscript: 'VFX_DUR_AURA_PULSE_GREEN_WHITE' },
  { label: 'Duration: aura pulse green/yellow', nwscript: 'VFX_DUR_AURA_PULSE_GREEN_YELLOW' },
  { label: 'Duration: aura pulse grey/black', nwscript: 'VFX_DUR_AURA_PULSE_GREY_BLACK' },
  { label: 'Duration: aura pulse grey/white', nwscript: 'VFX_DUR_AURA_PULSE_GREY_WHITE' },
  { label: 'Duration: aura pulse magenta/black', nwscript: 'VFX_DUR_AURA_PULSE_MAGENTA_BLACK' },
  { label: 'Duration: aura pulse magenta/blue', nwscript: 'VFX_DUR_AURA_PULSE_MAGENTA_BLUE' },
  { label: 'Duration: aura pulse magenta/green', nwscript: 'VFX_DUR_AURA_PULSE_MAGENTA_GREEN' },
  { label: 'Duration: aura pulse magenta/red', nwscript: 'VFX_DUR_AURA_PULSE_MAGENTA_RED' },
  { label: 'Duration: aura pulse magenta/white', nwscript: 'VFX_DUR_AURA_PULSE_MAGENTA_WHITE' },
  { label: 'Duration: aura pulse magenta/yellow', nwscript: 'VFX_DUR_AURA_PULSE_MAGENTA_YELLOW' },
  { label: 'Duration: aura pulse orange/black', nwscript: 'VFX_DUR_AURA_PULSE_ORANGE_BLACK' },
  { label: 'Duration: aura pulse orange/white', nwscript: 'VFX_DUR_AURA_PULSE_ORANGE_WHITE' },
  { label: 'Duration: aura pulse purple/black', nwscript: 'VFX_DUR_AURA_PULSE_PURPLE_BLACK' },
  { label: 'Duration: aura pulse purple/white', nwscript: 'VFX_DUR_AURA_PULSE_PURPLE_WHITE' },
  { label: 'Duration: aura pulse red/black', nwscript: 'VFX_DUR_AURA_PULSE_RED_BLACK' },
  { label: 'Duration: aura pulse red/blue', nwscript: 'VFX_DUR_AURA_PULSE_RED_BLUE' },
  { label: 'Duration: aura pulse red/green', nwscript: 'VFX_DUR_AURA_PULSE_RED_GREEN' },
  { label: 'Duration: aura pulse red/orange', nwscript: 'VFX_DUR_AURA_PULSE_RED_ORANGE' },
  { label: 'Duration: aura pulse red/white', nwscript: 'VFX_DUR_AURA_PULSE_RED_WHITE' },
  { label: 'Duration: aura pulse red/yellow', nwscript: 'VFX_DUR_AURA_PULSE_RED_YELLOW' },
  { label: 'Duration: aura pulse yellow/black', nwscript: 'VFX_DUR_AURA_PULSE_YELLOW_BLACK' },
  { label: 'Duration: aura pulse yellow/orange', nwscript: 'VFX_DUR_AURA_PULSE_YELLOW_ORANGE' },
  { label: 'Duration: aura pulse yellow/white', nwscript: 'VFX_DUR_AURA_PULSE_YELLOW_WHITE' },
  { label: 'Duration: aura purple', nwscript: 'VFX_DUR_AURA_PURPLE' },
  { label: 'Duration: aura red', nwscript: 'VFX_DUR_AURA_RED' },
  { label: 'Duration: aura red, dark', nwscript: 'VFX_DUR_AURA_RED_DARK' },
  { label: 'Duration: aura red, light', nwscript: 'VFX_DUR_AURA_RED_LIGHT' },
  { label: 'Duration: aura silence', nwscript: 'VFX_DUR_AURA_SILENCE' },
  { label: 'Duration: aura unearthly', nwscript: 'VFX_IMP_AURA_UNEARTHLY' },
  { label: 'Duration: aura white', nwscript: 'VFX_DUR_AURA_WHITE' },
  { label: 'Duration: aura yellow', nwscript: 'VFX_DUR_AURA_YELLOW' },
  { label: 'Duration: aura yellow, dark', nwscript: 'VFX_DUR_AURA_YELLOW_DARK' },
  { label: 'Duration: aura yellow, light', nwscript: 'VFX_DUR_AURA_YELLOW_LIGHT' },
  { label: 'Duration: bard song', nwscript: 'VFX_DUR_BARD_SONG' },
  { label: 'Duration: bard song (silent)', nwscript: '468' },
  { label: 'Duration: bard song, evil', nwscript: '507' },
  { label: 'Duration: Bigby\'s clenched fist', nwscript: 'VFX_DUR_BIGBYS_CLENCHED_FIST' },
  { label: 'Duration: Bigby\'s crushing hand', nwscript: 'VFX_DUR_BIGBYS_CRUSHING_HAND' },
  { label: 'Duration: Bigby\'s grasping hand', nwscript: 'VFX_DUR_BIGBYS_GRASPING_HAND' },
  { label: 'Duration: Bigby\'s interposing hand', nwscript: 'VFX_DUR_BIGBYS_INTERPOSING_HAND' },
  { label: 'Duration: blackout', nwscript: 'VFX_DUR_BLACKOUT' },
  { label: 'Duration: blind', nwscript: 'VFX_DUR_BLIND' },
  { label: 'Duration: blindvision', nwscript: 'VFX_DUR_BLINDVISION' },
  { label: 'Duration: blur', nwscript: 'VFX_DUR_BLUR' },
  { label: 'Duration: bubbles', nwscript: 'VFX_DUR_BUBBLES' },
  { label: 'Duration: caltrops', nwscript: 'VFX_DUR_CALTROPS' },
  { label: 'Duration: cessate negative', nwscript: 'VFX_DUR_CESSATE_NEGATIVE' },
  { label: 'Duration: cessate neutral', nwscript: 'VFX_DUR_CESSATE_NEUTRAL' },
  { label: 'Duration: cessate positive', nwscript: 'VFX_DUR_CESSATE_POSITIVE' },
  { label: 'Duration: cutscene invisibility', nwscript: 'VFX_DUR_CUTSCENE_INVISIBILITY' },
  { label: 'Duration: darkness', nwscript: 'VFX_DUR_DARKNESS' },
  { label: 'Duration: darkvision', nwscript: 'VFX_DUR_DARKVISION' },
  { label: 'Duration: death armor', nwscript: 'VFX_DUR_DEATH_ARMOR' },
  { label: 'Duration: DLA shield map', nwscript: '619' },
  { label: 'Duration: elemental shield', nwscript: 'VFX_DUR_ELEMENTAL_SHIELD' },
  { label: 'Duration: entangle', nwscript: 'VFX_DUR_ENTANGLE' },
  { label: 'Duration: ethereal visage', nwscript: 'VFX_DUR_ETHEREAL_VISAGE' },
  { label: 'Duration: flag, blue', nwscript: 'VFX_DUR_FLAG_BLUE' },
  { label: 'Duration: flag, gold', nwscript: 'VFX_DUR_FLAG_GOLD_FIXED' },
  { label: 'Duration: flag, purple', nwscript: 'VFX_DUR_FLAG_PURPLE_FIXED' },
  { label: 'Duration: flag, red', nwscript: 'VFX_DUR_FLAG_RED' },
  { label: 'Duration: flies', nwscript: 'VFX_DUR_FLIES' },
  { label: 'Duration: freedom of movement', nwscript: 'VFX_DUR_FREEDOM_OF_MOVEMENT' },
  { label: 'Duration: freeze animation', nwscript: 'VFX_DUR_FREEZE_ANIMATION' },
  { label: 'Duration: ghost smoke', nwscript: 'VFX_DUR_GHOST_SMOKE' },
  { label: 'Duration: ghost smoke 2', nwscript: 'VFX_DUR_GHOST_SMOKE_2' },
  { label: 'Duration: ghost transparent', nwscript: 'VFX_DUR_GHOST_TRANSPARENT' },
  { label: 'Duration: ghostly pulse', nwscript: 'VFX_DUR_GHOSTLY_PULSE' },
  { label: 'Duration: ghostly visage', nwscript: 'VFX_DUR_GHOSTLY_VISAGE' },
  { label: 'Duration: ghostly visage (no sound)', nwscript: 'VFX_DUR_GHOSTLY_VISAGE_NO_SOUND' },
  { label: 'Duration: globe, minor', nwscript: 'VFX_DUR_GLOBE_MINOR' },
  { label: 'Duration: globe of invulnerability', nwscript: 'VFX_DUR_GLOBE_INVULNERABILITY' },
  { label: 'Duration: glow blue', nwscript: 'VFX_DUR_GLOW_BLUE' },
  { label: 'Duration: glow brown', nwscript: 'VFX_DUR_GLOW_BROWN' },
  { label: 'Duration: glow green', nwscript: 'VFX_DUR_GLOW_GREEN' },
  { label: 'Duration: glow grey', nwscript: 'VFX_DUR_GLOW_GREY' },
  { label: 'Duration: glow light blue', nwscript: 'VFX_DUR_GLOW_LIGHT_BLUE' },
  { label: 'Duration: glow light brown', nwscript: 'VFX_DUR_GLOW_LIGHT_BROWN' },
  { label: 'Duration: glow light green', nwscript: 'VFX_DUR_GLOW_LIGHT_GREEN' },
  { label: 'Duration: glow light orange', nwscript: 'VFX_DUR_GLOW_LIGHT_ORANGE' },
  { label: 'Duration: glow light purple', nwscript: 'VFX_DUR_GLOW_LIGHT_PURPLE' },
  { label: 'Duration: glow light red', nwscript: 'VFX_DUR_GLOW_LIGHT_RED' },
  { label: 'Duration: glow light yellow', nwscript: 'VFX_DUR_GLOW_LIGHT_YELLOW' },
  { label: 'Duration: glow orange', nwscript: 'VFX_DUR_GLOW_ORANGE' },
  { label: 'Duration: glow purple', nwscript: 'VFX_DUR_GLOW_PURPLE' },
  { label: 'Duration: glow red', nwscript: 'VFX_DUR_GLOW_RED' },
  { label: 'Duration: glow white', nwscript: 'VFX_DUR_GLOW_WHITE' },
  { label: 'Duration: glow yellow', nwscript: 'VFX_DUR_GLOW_YELLOW' },
  { label: 'Duration: glyph of warding', nwscript: 'VFX_DUR_GLYPH_OF_WARDING' },
  { label: 'Duration: iceskin', nwscript: 'VFX_DUR_ICESKIN' },
  { label: 'Duration: inferno', nwscript: 'VFX_DUR_INFERNO' },
  { label: 'Duration: inferno (no sound)', nwscript: 'VFX_DUR_INFERNO_NO_SOUND' },
  { label: 'Duration: inferno chest', nwscript: 'VFX_DUR_INFERNO_CHEST' },
  { label: 'Duration: invisibility', nwscript: 'VFX_DUR_INVISIBILITY' },
  { label: 'Duration: iounstone', nwscript: 'VFX_DUR_IOUNSTONE' },
  { label: 'Duration: iounstone blue', nwscript: 'VFX_DUR_IOUNSTONE_BLUE' },
  { label: 'Duration: iounstone green', nwscript: 'VFX_DUR_IOUNSTONE_GREEN' },
  { label: 'Duration: iounstone red', nwscript: 'VFX_DUR_IOUNSTONE_RED' },
  { label: 'Duration: iounstone yellow', nwscript: 'VFX_DUR_IOUNSTONE_YELLOW' },
  { label: 'Duration: leaves', nwscript: '132' },
  { label: 'Duration: light', nwscript: 'VFX_DUR_LIGHT' },
  { label: 'Duration: light, blue 5', nwscript: 'VFX_DUR_LIGHT_BLUE_5' },
  { label: 'Duration: light, blue 10', nwscript: 'VFX_DUR_LIGHT_BLUE_10' },
  { label: 'Duration: light, blue 15', nwscript: 'VFX_DUR_LIGHT_BLUE_15' },
  { label: 'Duration: light, blue 20', nwscript: 'VFX_DUR_LIGHT_BLUE_20' },
  { label: 'Duration: light, grey 5', nwscript: 'VFX_DUR_LIGHT_GREY_5' },
  { label: 'Duration: light, grey 10', nwscript: 'VFX_DUR_LIGHT_GREY_10' },
  { label: 'Duration: light, grey 15', nwscript: 'VFX_DUR_LIGHT_GREY_15' },
  { label: 'Duration: light, grey 20', nwscript: 'VFX_DUR_LIGHT_GREY_20' },
  { label: 'Duration: light, orange 5', nwscript: 'VFX_DUR_LIGHT_ORANGE_5' },
  { label: 'Duration: light, orange 10', nwscript: 'VFX_DUR_LIGHT_ORANGE_10' },
  { label: 'Duration: light, orange 15', nwscript: 'VFX_DUR_LIGHT_ORANGE_15' },
  { label: 'Duration: light, orange 20', nwscript: 'VFX_DUR_LIGHT_ORANGE_20' },
  { label: 'Duration: light, purple 5', nwscript: 'VFX_DUR_LIGHT_PURPLE_5' },
  { label: 'Duration: light, purple 10', nwscript: 'VFX_DUR_LIGHT_PURPLE_10' },
  { label: 'Duration: light, purple 15', nwscript: 'VFX_DUR_LIGHT_PURPLE_15' },
  { label: 'Duration: light, purple 20', nwscript: 'VFX_DUR_LIGHT_PURPLE_20' },
  { label: 'Duration: light, red 5', nwscript: 'VFX_DUR_LIGHT_RED_5' },
  { label: 'Duration: light, red 10', nwscript: 'VFX_DUR_LIGHT_RED_10' },
  { label: 'Duration: light, red 15', nwscript: 'VFX_DUR_LIGHT_RED_15' },
  { label: 'Duration: light, red 20', nwscript: 'VFX_DUR_LIGHT_RED_20' },
  { label: 'Duration: light, white 5', nwscript: 'VFX_DUR_LIGHT_WHITE_5' },
  { label: 'Duration: light, white 10', nwscript: 'VFX_DUR_LIGHT_WHITE_10' },
  { label: 'Duration: light, white 15', nwscript: 'VFX_DUR_LIGHT_WHITE_15' },
  { label: 'Duration: light, white 20', nwscript: 'VFX_DUR_LIGHT_WHITE_20' },
  { label: 'Duration: light, yellow 5', nwscript: 'VFX_DUR_LIGHT_YELLOW_5' },
  { label: 'Duration: light, yellow 10', nwscript: 'VFX_DUR_LIGHT_YELLOW_10' },
  { label: 'Duration: light, yellow 15', nwscript: 'VFX_DUR_LIGHT_YELLOW_15' },
  { label: 'Duration: light, yellow 20', nwscript: 'VFX_DUR_LIGHT_YELLOW_20' },
  { label: 'Duration: low-light vision', nwscript: 'VFX_DUR_LOWLIGHTVISION' },
  { label: 'Duration: magic resistance', nwscript: 'VFX_DUR_MAGIC_RESISTANCE' },
  { label: 'Duration: magical sight', nwscript: 'VFX_DUR_MAGICAL_SIGHT' },
  { label: 'Duration: mind-affecting disabled', nwscript: 'VFX_DUR_MIND_AFFECTING_DISABLED' },
  { label: 'Duration: mind-affecting dominated', nwscript: 'VFX_DUR_MIND_AFFECTING_DOMINATED' },
  { label: 'Duration: mind-affecting fear', nwscript: 'VFX_DUR_MIND_AFFECTING_FEAR' },
  { label: 'Duration: mind-affecting negative', nwscript: 'VFX_DUR_MIND_AFFECTING_NEGATIVE' },
  { label: 'Duration: mind-affecting positive', nwscript: 'VFX_DUR_MIND_AFFECTING_POSITIVE' },
  { label: 'Duration: paralyze/hold', nwscript: 'VFX_DUR_PARALYZE_HOLD' },
  { label: 'Duration: paralyzed', nwscript: 'VFX_DUR_PARALYZED' },
  { label: 'Duration: PDK fear', nwscript: 'VFX_DUR_PDK_FEAR' },
  { label: 'Duration: petrify', nwscript: 'VFX_DUR_PETRIFY' },
  { label: 'Duration: pixiedust', nwscript: 'VFX_DUR_PIXIEDUST' },
  { label: 'Duration: prot acid shield', nwscript: '448' },
  { label: 'Duration: prot barkskin', nwscript: 'VFX_DUR_PROT_BARKSKIN' },
  { label: 'Duration: prot epic armor', nwscript: 'VFX_DUR_PROT_EPIC_ARMOR' },
  { label: 'Duration: prot epic armor 2', nwscript: 'VFX_DUR_PROT_EPIC_ARMOR_2' },
  { label: 'Duration: prot greater stoneskin', nwscript: 'VFX_DUR_PROT_GREATER_STONESKIN' },
  { label: 'Duration: prot premonition', nwscript: 'VFX_DUR_PROT_PREMONITION' },
  { label: 'Duration: prot shadow armor', nwscript: 'VFX_DUR_PROT_SHADOW_ARMOR' },
  { label: 'Duration: prot stoneskin', nwscript: 'VFX_DUR_PROT_STONESKIN' },
  { label: 'Duration: protection from elements', nwscript: 'VFX_DUR_PROTECTION_ELEMENTS' },
  { label: 'Duration: protection from evil, major', nwscript: 'VFX_DUR_PROTECTION_EVIL_MAJOR' },
  { label: 'Duration: protection from evil, minor', nwscript: 'VFX_DUR_PROTECTION_EVIL_MINOR' },
  { label: 'Duration: protection from good, major', nwscript: 'VFX_DUR_PROTECTION_GOOD_MAJOR' },
  { label: 'Duration: protection from good, minor', nwscript: 'VFX_DUR_PROTECTION_GOOD_MINOR' },
  { label: 'Duration: quill in chest', nwscript: 'VFX_DUR_QUILL_IN_CHEST' },
  { label: 'Duration: sanctuary', nwscript: 'VFX_DUR_SANCTUARY' },
  { label: 'Duration: smoke', nwscript: 'VFX_DUR_SMOKE' },
  { label: 'Duration: spellturning', nwscript: 'VFX_DUR_SPELLTURNING' },
  { label: 'Duration: stonehold', nwscript: 'VFX_DUR_STONEHOLD' },
  { label: 'Duration: tentacle', nwscript: 'VFX_DUR_TENTACLE' },
  { label: 'Duration: ultravision', nwscript: 'VFX_DUR_ULTRAVISION' },
  { label: 'Duration: unsupported animal cage', nwscript: '509' },
  { label: 'Duration: unsupported cage', nwscript: '508' },
  { label: 'Duration: unsupported flame, large', nwscript: '510' },
  { label: 'Duration: web', nwscript: 'VFX_DUR_WEB' },
  { label: 'Duration: web mass', nwscript: 'VFX_DUR_WEB_MASS' },
  { label: 'Eyes: blue dwarf female', nwscript: '327' },
  { label: 'Eyes: blue dwarf male', nwscript: '326' },
  { label: 'Eyes: blue elf female', nwscript: '329' },
  { label: 'Eyes: blue elf male', nwscript: '328' },
  { label: 'Eyes: blue gnome female', nwscript: '331' },
  { label: 'Eyes: blue gnome male', nwscript: '330' },
  { label: 'Eyes: blue half-orc female', nwscript: '335' },
  { label: 'Eyes: blue half-orc male', nwscript: '334' },
  { label: 'Eyes: blue halfling female', nwscript: '333' },
  { label: 'Eyes: blue halfling male', nwscript: '332' },
  { label: 'Eyes: blue human/half-elf female', nwscript: '325' },
  { label: 'Eyes: blue human/half-elf male', nwscript: '324' },
  { label: 'Eyes: blue troglodyte', nwscript: '336' },
  { label: 'Eyes: cyan dwarf female', nwscript: 'VFX_EYES_CYN_DWARF_FEMALE' },
  { label: 'Eyes: cyan dwarf male', nwscript: 'VFX_EYES_CYN_DWARF_MALE' },
  { label: 'Eyes: cyan elf female', nwscript: 'VFX_EYES_CYN_ELF_FEMALE' },
  { label: 'Eyes: cyan elf male', nwscript: 'VFX_EYES_CYN_ELF_MALE' },
  { label: 'Eyes: cyan gnome female', nwscript: 'VFX_EYES_CYN_GNOME_FEMALE' },
  { label: 'Eyes: cyan gnome male', nwscript: 'VFX_EYES_CYN_GNOME_MALE' },
  { label: 'Eyes: cyan half-orc female', nwscript: 'VFX_EYES_CYN_HALFORC_FEMALE' },
  { label: 'Eyes: cyan half-orc male', nwscript: 'VFX_EYES_CYN_HALFORC_MALE' },
  { label: 'Eyes: cyan halfling female', nwscript: 'VFX_EYES_CYN_HALFLING_FEMALE' },
  { label: 'Eyes: cyan halfling male', nwscript: 'VFX_EYES_CYN_HALFLING_MALE' },
  { label: 'Eyes: cyan human/half-elf female', nwscript: 'VFX_EYES_CYN_HUMAN_FEMALE' },
  { label: 'Eyes: cyan human/half-elf male', nwscript: 'VFX_EYES_CYN_HUMAN_MALE' },
  { label: 'Eyes: cyan troglodyte', nwscript: 'VFX_EYES_CYN_TROGLODYTE' },
  { label: 'Eyes: green dwarf female', nwscript: 'VFX_EYES_GREEN_DWARF_FEMALE' },
  { label: 'Eyes: green dwarf male', nwscript: 'VFX_EYES_GREEN_DWARF_MALE' },
  { label: 'Eyes: green elf female', nwscript: 'VFX_EYES_GREEN_ELF_FEMALE' },
  { label: 'Eyes: green elf male', nwscript: 'VFX_EYES_GREEN_ELF_MALE' },
  { label: 'Eyes: green gnome female', nwscript: 'VFX_EYES_GREEN_GNOME_FEMALE' },
  { label: 'Eyes: green gnome male', nwscript: 'VFX_EYES_GREEN_GNOME_MALE' },
  { label: 'Eyes: green half-orc female', nwscript: 'VFX_EYES_GREEN_HALFORC_FEMALE' },
  { label: 'Eyes: green half-orc male', nwscript: 'VFX_EYES_GREEN_HALFORC_MALE' },
  { label: 'Eyes: green halfling female', nwscript: 'VFX_EYES_GREEN_HALFLING_FEMALE' },
  { label: 'Eyes: green halfling male', nwscript: 'VFX_EYES_GREEN_HALFLING_MALE' },
  { label: 'Eyes: green human/half-elf female', nwscript: 'VFX_EYES_GREEN_HUMAN_FEMALE' },
  { label: 'Eyes: green human/half-elf male', nwscript: 'VFX_EYES_GREEN_HUMAN_MALE' },
  { label: 'Eyes: green troglodyte', nwscript: 'VFX_EYES_GREEN_TROGLODYTE' },
  { label: 'Eyes: orange dwarf female', nwscript: 'VFX_EYES_ORG_DWARF_FEMALE' },
  { label: 'Eyes: orange dwarf male', nwscript: 'VFX_EYES_ORG_DWARF_MALE' },
  { label: 'Eyes: orange elf female', nwscript: 'VFX_EYES_ORG_ELF_FEMALE' },
  { label: 'Eyes: orange elf male', nwscript: 'VFX_EYES_ORG_ELF_MALE' },
  { label: 'Eyes: orange gnome female', nwscript: 'VFX_EYES_ORG_GNOME_FEMALE' },
  { label: 'Eyes: orange gnome male', nwscript: 'VFX_EYES_ORG_GNOME_MALE' },
  { label: 'Eyes: orange half-orc female', nwscript: 'VFX_EYES_ORG_HALFORC_FEMALE' },
  { label: 'Eyes: orange half-orc male', nwscript: 'VFX_EYES_ORG_HALFORC_MALE' },
  { label: 'Eyes: orange halfling female', nwscript: 'VFX_EYES_ORG_HALFLING_FEMALE' },
  { label: 'Eyes: orange halfling male', nwscript: 'VFX_EYES_ORG_HALFLING_MALE' },
  { label: 'Eyes: orange human/half-elf female', nwscript: 'VFX_EYES_ORG_HUMAN_FEMALE' },
  { label: 'Eyes: orange human/half-elf male', nwscript: 'VFX_EYES_ORG_HUMAN_MALE' },
  { label: 'Eyes: orange troglodyte', nwscript: 'VFX_EYES_ORG_TROGLODYTE' },
  { label: 'Eyes: purple dwarf female', nwscript: 'VFX_EYES_PUR_DWARF_FEMALE' },
  { label: 'Eyes: purple dwarf male', nwscript: 'VFX_EYES_PUR_DWARF_MALE' },
  { label: 'Eyes: purple elf female', nwscript: 'VFX_EYES_PUR_ELF_FEMALE' },
  { label: 'Eyes: purple elf male', nwscript: 'VFX_EYES_PUR_ELF_MALE' },
  { label: 'Eyes: purple gnome female', nwscript: 'VFX_EYES_PUR_GNOME_FEMALE' },
  { label: 'Eyes: purple gnome male', nwscript: 'VFX_EYES_PUR_GNOME_MALE' },
  { label: 'Eyes: purple half-orc female', nwscript: 'VFX_EYES_PUR_HALFORC_FEMALE' },
  { label: 'Eyes: purple half-orc male', nwscript: 'VFX_EYES_PUR_HALFORC_MALE' },
  { label: 'Eyes: purple halfling female', nwscript: 'VFX_EYES_PUR_HALFLING_FEMALE' },
  { label: 'Eyes: purple halfling male', nwscript: 'VFX_EYES_PUR_HALFLING_MALE' },
  { label: 'Eyes: purple human/half-elf female', nwscript: 'VFX_EYES_PUR_HUMAN_FEMALE' },
  { label: 'Eyes: purple human/half-elf male', nwscript: 'VFX_EYES_PUR_HUMAN_MALE' },
  { label: 'Eyes: purple troglodyte', nwscript: 'VFX_EYES_PUR_TROGLODYTE' },
  { label: 'Eyes: red flame dwarf female', nwscript: 'VFX_EYES_RED_FLAME_DWARF_FEMALE' },
  { label: 'Eyes: red flame dwarf male', nwscript: 'VFX_EYES_RED_FLAME_DWARF_MALE' },
  { label: 'Eyes: red flame elf female', nwscript: 'VFX_EYES_RED_FLAME_ELF_FEMALE' },
  { label: 'Eyes: red flame elf male', nwscript: 'VFX_EYES_RED_FLAME_ELF_MALE' },
  { label: 'Eyes: red flame gnome female', nwscript: 'VFX_EYES_RED_FLAME_GNOME_FEMALE' },
  { label: 'Eyes: red flame gnome male', nwscript: 'VFX_EYES_RED_FLAME_GNOME_MALE' },
  { label: 'Eyes: red flame half-orc female', nwscript: 'VFX_EYES_RED_FLAME_HALFORC_FEMALE' },
  { label: 'Eyes: red flame half-orc male', nwscript: 'VFX_EYES_RED_FLAME_HALFORC_MALE' },
  { label: 'Eyes: red flame halfling female', nwscript: 'VFX_EYES_RED_FLAME_HALFLING_FEMALE' },
  { label: 'Eyes: red flame halfling male', nwscript: 'VFX_EYES_RED_FLAME_HALFLING_MALE' },
  { label: 'Eyes: red flame human/half-elf female', nwscript: 'VFX_EYES_RED_FLAME_HUMAN_FEMALE' },
  { label: 'Eyes: red flame human/half-elf male', nwscript: 'VFX_EYES_RED_FLAME_HUMAN_MALE' },
  { label: 'Eyes: red flame troglodyte', nwscript: 'VFX_EYES_RED_FLAME_TROGLODYTE' },
  { label: 'Eyes: white dwarf female', nwscript: 'VFX_EYES_WHT_DWARF_FEMALE' },
  { label: 'Eyes: white dwarf male', nwscript: 'VFX_EYES_WHT_DWARF_MALE' },
  { label: 'Eyes: white elf female', nwscript: 'VFX_EYES_WHT_ELF_FEMALE' },
  { label: 'Eyes: white elf male', nwscript: 'VFX_EYES_WHT_ELF_MALE' },
  { label: 'Eyes: white gnome female', nwscript: 'VFX_EYES_WHT_GNOME_FEMALE' },
  { label: 'Eyes: white gnome male', nwscript: 'VFX_EYES_WHT_GNOME_MALE' },
  { label: 'Eyes: white half-orc female', nwscript: 'VFX_EYES_WHT_HALFORC_FEMALE' },
  { label: 'Eyes: white half-orc male', nwscript: 'VFX_EYES_WHT_HALFORC_MALE' },
  { label: 'Eyes: white halfling female', nwscript: 'VFX_EYES_WHT_HALFLING_FEMALE' },
  { label: 'Eyes: white halfling male', nwscript: 'VFX_EYES_WHT_HALFLING_MALE' },
  { label: 'Eyes: white human/half-elf female', nwscript: 'VFX_EYES_WHT_HUMAN_FEMALE' },
  { label: 'Eyes: white human/half-elf male', nwscript: 'VFX_EYES_WHT_HUMAN_MALE' },
  { label: 'Eyes: white troglodyte', nwscript: 'VFX_EYES_WHT_TROGLODYTE' },
  { label: 'Eyes: yellow dwarf female', nwscript: 'VFX_EYES_YEL_DWARF_FEMALE' },
  { label: 'Eyes: yellow dwarf male', nwscript: 'VFX_EYES_YEL_DWARF_MALE' },
  { label: 'Eyes: yellow elf female', nwscript: 'VFX_EYES_YEL_ELF_FEMALE' },
  { label: 'Eyes: yellow elf male', nwscript: 'VFX_EYES_YEL_ELF_MALE' },
  { label: 'Eyes: yellow gnome female', nwscript: 'VFX_EYES_YEL_GNOME_FEMALE' },
  { label: 'Eyes: yellow gnome male', nwscript: 'VFX_EYES_YEL_GNOME_MALE' },
  { label: 'Eyes: yellow half-orc female', nwscript: 'VFX_EYES_YEL_HALFORC_FEMALE' },
  { label: 'Eyes: yellow half-orc male', nwscript: 'VFX_EYES_YEL_HALFORC_MALE' },
  { label: 'Eyes: yellow halfling female', nwscript: 'VFX_EYES_YEL_HALFLING_FEMALE' },
  { label: 'Eyes: yellow halfling male', nwscript: 'VFX_EYES_YEL_HALFLING_MALE' },
  { label: 'Eyes: yellow human/half-elf female', nwscript: 'VFX_EYES_YEL_HUMAN_FEMALE' },
  { label: 'Eyes: yellow human/half-elf male', nwscript: 'VFX_EYES_YEL_HUMAN_MALE' },
  { label: 'Eyes: yellow troglodyte', nwscript: 'VFX_EYES_YEL_TROGLODYTE' },
  { label: 'Scene: black tile', nwscript: '506' },
  { label: 'Scene: building', nwscript: '449' },
  { label: 'Scene: burned rubble 1', nwscript: '450' },
  { label: 'Scene: burned rubble 2', nwscript: '454' },
  { label: 'Scene: burning half house', nwscript: '451' },
  { label: 'Scene: evil castle wall', nwscript: '443' },
  { label: 'Scene: formian 1', nwscript: '404' },
  { label: 'Scene: formian 2', nwscript: '405' },
  { label: 'Scene: gazebo', nwscript: '457' },
  { label: 'Scene: grass', nwscript: '402' },
  { label: 'Scene: ice', nwscript: '426' },
  { label: 'Scene: ice, clear', nwscript: '442' },
  { label: 'Scene: lava 1', nwscript: '349' },
  { label: 'Scene: lava 2', nwscript: '350' },
  { label: 'Scene: market 1', nwscript: '455' },
  { label: 'Scene: market 2', nwscript: '456' },
  { label: 'Scene: MF ant hill', nwscript: '441' },
  { label: 'Scene: MF bricks w/ hanging light', nwscript: '436' },
  { label: 'Scene: MF cave interior', nwscript: '435' },
  { label: 'Scene: MF caravan wagon', nwscript: '439' },
  { label: 'Scene: MF dirt pile', nwscript: '434' },
  { label: 'Scene: MF graveyard', nwscript: '440' },
  { label: 'Scene: MF groundcover 1', nwscript: '429' },
  { label: 'Scene: MF groundcover 2', nwscript: '430' },
  { label: 'Scene: MF house', nwscript: '438' },
  { label: 'Scene: MF market stall', nwscript: '432' },
  { label: 'Scene: MF pillar', nwscript: '427' },
  { label: 'Scene: MF ruins', nwscript: '433' },
  { label: 'Scene: MF water (below ground level)', nwscript: '437' },
  { label: 'Scene: MF waterfall', nwscript: '428' },
  { label: 'Scene: MF waterfall 2', nwscript: '431' },
  { label: 'Scene: pit trap', nwscript: '406' },
  { label: 'Scene: prison floor', nwscript: '511' },
  { label: 'Scene: ruined arch', nwscript: '452' },
  { label: 'Scene: solid arch', nwscript: '453' },
  { label: 'Scene: temple', nwscript: '348' },
  { label: 'Scene: tilt rail', nwscript: '642' },
  { label: 'Scene: tilt rail, small', nwscript: '643' },
  { label: 'Scene: tilt rail end', nwscript: '640' },
  { label: 'Scene: tilt rail end, small', nwscript: '641' },
  { label: 'Scene: tower', nwscript: '347' },
  { label: 'Scene: wagon', nwscript: '458' },
  { label: 'Scene: water', nwscript: '401' },
  { label: 'Scene: weird', nwscript: '323' },
  { label: 'Scene: well', nwscript: '358' },
];

// VFX_IMPACT: 229 entries
export const VFX_IMPACT = [
  { label: 'No visual effect', nwscript: 'VFX_NONE' },
  { label: 'Common: blood crt green', nwscript: 'VFX_COM_BLOOD_CRT_GREEN' },
  { label: 'Common: blood crt green head', nwscript: '492' },
  { label: 'Common: blood crt red', nwscript: 'VFX_COM_BLOOD_CRT_RED' },
  { label: 'Common: blood crt red head', nwscript: '491' },
  { label: 'Common: blood crt wimp', nwscript: 'VFX_COM_BLOOD_CRT_WIMP' },
  { label: 'Common: blood crt wimp green', nwscript: '301' },
  { label: 'Common: blood crt wimp yellow', nwscript: '298' },
  { label: 'Common: blood crt yellow', nwscript: 'VFX_COM_BLOOD_CRT_YELLOW' },
  { label: 'Common: blood crt yellow head', nwscript: '493' },
  { label: 'Common: blood lrg green', nwscript: 'VFX_COM_BLOOD_LRG_GREEN' },
  { label: 'Common: blood lrg red', nwscript: 'VFX_COM_BLOOD_LRG_RED' },
  { label: 'Common: blood lrg wimp', nwscript: 'VFX_COM_BLOOD_LRG_WIMP' },
  { label: 'Common: blood lrg wimp green', nwscript: '300' },
  { label: 'Common: blood lrg wimp yellow', nwscript: '297' },
  { label: 'Common: blood lrg yellow', nwscript: 'VFX_COM_BLOOD_LRG_YELLOW' },
  { label: 'Common: blood reg green', nwscript: 'VFX_COM_BLOOD_REG_GREEN' },
  { label: 'Common: blood reg red', nwscript: 'VFX_COM_BLOOD_REG_RED' },
  { label: 'Common: blood reg wimp', nwscript: 'VFX_COM_BLOOD_REG_WIMP' },
  { label: 'Common: blood reg wimp green', nwscript: '299' },
  { label: 'Common: blood reg wimp yellow', nwscript: '296' },
  { label: 'Common: blood reg yellow', nwscript: 'VFX_COM_BLOOD_REG_YELLOW' },
  { label: 'Common: blood spark large', nwscript: 'VFX_COM_BLOOD_SPARK_LARGE' },
  { label: 'Common: blood spark medium', nwscript: 'VFX_COM_BLOOD_SPARK_MEDIUM' },
  { label: 'Common: blood spark small', nwscript: 'VFX_COM_BLOOD_SPARK_SMALL' },
  { label: 'Common: chunk bone medium', nwscript: 'VFX_COM_CHUNK_BONE_MEDIUM' },
  { label: 'Common: chunk green medium', nwscript: 'VFX_COM_CHUNK_GREEN_MEDIUM' },
  { label: 'Common: chunk green small', nwscript: 'VFX_COM_CHUNK_GREEN_SMALL' },
  { label: 'Common: chunk red ballista', nwscript: 'VFX_COM_CHUNK_RED_BALLISTA' },
  { label: 'Common: chunk red large', nwscript: 'VFX_COM_CHUNK_RED_LARGE' },
  { label: 'Common: chunk red medium', nwscript: 'VFX_COM_CHUNK_RED_MEDIUM' },
  { label: 'Common: chunk red small', nwscript: 'VFX_COM_CHUNK_RED_SMALL' },
  { label: 'Common: chunk stone medium', nwscript: 'VFX_COM_CHUNK_STONE_MEDIUM' },
  { label: 'Common: chunk stone small', nwscript: 'VFX_COM_CHUNK_STONE_SMALL' },
  { label: 'Common: chunk yellow medium', nwscript: 'VFX_COM_CHUNK_YELLOW_MEDIUM' },
  { label: 'Common: chunk yellow small', nwscript: 'VFX_COM_CHUNK_YELLOW_SMALL' },
  { label: 'Common: hit acid', nwscript: 'VFX_COM_HIT_ACID' },
  { label: 'Common: hit divine', nwscript: 'VFX_COM_HIT_DIVINE' },
  { label: 'Common: hit electrical', nwscript: 'VFX_COM_HIT_ELECTRICAL' },
  { label: 'Common: hit fire', nwscript: 'VFX_COM_HIT_FIRE' },
  { label: 'Common: hit frost', nwscript: 'VFX_COM_HIT_FROST' },
  { label: 'Common: hit negative', nwscript: 'VFX_COM_HIT_NEGATIVE' },
  { label: 'Common: hit sonic', nwscript: 'VFX_COM_HIT_SONIC' },
  { label: 'Common: sparks parry', nwscript: 'VFX_COM_SPARKS_PARRY' },
  { label: 'Common: special blue/red', nwscript: 'VFX_COM_SPECIAL_BLUE_RED' },
  { label: 'Common: special pink/orange', nwscript: 'VFX_COM_SPECIAL_PINK_ORANGE' },
  { label: 'Common: special red/orange', nwscript: 'VFX_COM_SPECIAL_RED_ORANGE' },
  { label: 'Common: special red/white', nwscript: 'VFX_COM_SPECIAL_RED_WHITE' },
  { label: 'Common: special white/blue', nwscript: 'VFX_COM_SPECIAL_WHITE_BLUE' },
  { label: 'Common: special white/orange', nwscript: 'VFX_COM_SPECIAL_WHITE_ORANGE' },
  { label: 'Common: unload model', nwscript: 'VFX_COM_UNLOAD_MODEL' },
  { label: 'Conjure: fire', nwscript: '467' },
  { label: 'Conjure: mind', nwscript: '466' },
  { label: 'Fire-and-forget: blind/deaf', nwscript: 'VFX_FNF_BLINDDEAF' },
  { label: 'Fire-and-forget: deck', nwscript: 'VFX_FNF_DECK' },
  { label: 'Fire-and-forget: demon hand', nwscript: 'VFX_FNF_DEMON_HAND' },
  { label: 'Fire-and-forget: dispel', nwscript: 'VFX_FNF_DISPEL' },
  { label: 'Fire-and-forget: dispel, disjunction', nwscript: 'VFX_FNF_DISPEL_DISJUNCTION' },
  { label: 'Fire-and-forget: dispel, greater', nwscript: 'VFX_FNF_DISPEL_GREATER' },
  { label: 'Fire-and-forget: dragon breath, ground', nwscript: '494' },
  { label: 'Fire-and-forget: electric explosion', nwscript: 'VFX_FNF_ELECTRIC_EXPLOSION' },
  { label: 'Fire-and-forget: fireball', nwscript: 'VFX_FNF_FIREBALL' },
  { label: 'Fire-and-forget: firestorm', nwscript: 'VFX_FNF_FIRESTORM' },
  { label: 'Fire-and-forget: gas explosion acid', nwscript: 'VFX_FNF_GAS_EXPLOSION_ACID' },
  { label: 'Fire-and-forget: gas explosion evil', nwscript: 'VFX_FNF_GAS_EXPLOSION_EVIL' },
  { label: 'Fire-and-forget: gas explosion fire', nwscript: 'VFX_FNF_GAS_EXPLOSION_FIRE' },
  { label: 'Fire-and-forget: gas explosion grease', nwscript: 'VFX_FNF_GAS_EXPLOSION_GREASE' },
  { label: 'Fire-and-forget: gas explosion mind', nwscript: 'VFX_FNF_GAS_EXPLOSION_MIND' },
  { label: 'Fire-and-forget: gas explosion nature', nwscript: 'VFX_FNF_GAS_EXPLOSION_NATURE' },
  { label: 'Fire-and-forget: greater ruin', nwscript: 'VFX_FNF_GREATER_RUIN' },
  { label: 'Fire-and-forget: hellball', nwscript: '464' },
  { label: 'Fire-and-forget: highlight flash white', nwscript: '294' },
  { label: 'Fire-and-forget: horrid wilting', nwscript: 'VFX_FNF_HORRID_WILTING' },
  { label: 'Fire-and-forget: howl mind', nwscript: 'VFX_FNF_HOWL_MIND' },
  { label: 'Fire-and-forget: howl odd', nwscript: 'VFX_FNF_HOWL_ODD' },
  { label: 'Fire-and-forget: howl war cry', nwscript: 'VFX_FNF_HOWL_WAR_CRY' },
  { label: 'Fire-and-forget: howl war cry, female', nwscript: 'VFX_FNF_HOWL_WAR_CRY_FEMALE' },
  { label: 'Fire-and-forget: icestorm', nwscript: 'VFX_FNF_ICESTORM' },
  { label: 'Fire-and-forget: implosion', nwscript: 'VFX_FNF_IMPLOSION' },
  { label: 'Fire-and-forget: LOS evil 10', nwscript: 'VFX_FNF_LOS_EVIL_10' },
  { label: 'Fire-and-forget: LOS evil 20', nwscript: 'VFX_FNF_LOS_EVIL_20' },
  { label: 'Fire-and-forget: LOS evil 30', nwscript: 'VFX_FNF_LOS_EVIL_30' },
  { label: 'Fire-and-forget: LOS holy 10', nwscript: 'VFX_FNF_LOS_HOLY_10' },
  { label: 'Fire-and-forget: LOS holy 20', nwscript: 'VFX_FNF_LOS_HOLY_20' },
  { label: 'Fire-and-forget: LOS holy 30', nwscript: 'VFX_FNF_LOS_HOLY_30' },
  { label: 'Fire-and-forget: LOS normal 10', nwscript: 'VFX_FNF_LOS_NORMAL_10' },
  { label: 'Fire-and-forget: LOS normal 20', nwscript: 'VFX_FNF_LOS_NORMAL_20' },
  { label: 'Fire-and-forget: LOS normal 30', nwscript: 'VFX_FNF_LOS_NORMAL_30' },
  { label: 'Fire-and-forget: meteor swarm', nwscript: 'VFX_FNF_METEOR_SWARM' },
  { label: 'Fire-and-forget: mystical explosion', nwscript: 'VFX_FNF_MYSTICAL_EXPLOSION' },
  { label: 'Fire-and-forget: nature\'s balance', nwscript: 'VFX_FNF_NATURES_BALANCE' },
  { label: 'Fire-and-forget: power word: kill', nwscript: 'VFX_FNF_PWKILL' },
  { label: 'Fire-and-forget: power word: stun', nwscript: 'VFX_FNF_PWSTUN' },
  { label: 'Fire-and-forget: screen bump', nwscript: 'VFX_FNF_SCREEN_BUMP' },
  { label: 'Fire-and-forget: screen shake', nwscript: 'VFX_FNF_SCREEN_SHAKE' },
  { label: 'Fire-and-forget: screen shake 2', nwscript: '356' },
  { label: 'Fire-and-forget: smoke puff', nwscript: 'VFX_FNF_SMOKE_PUFF' },
  { label: 'Fire-and-forget: sound burst', nwscript: 'VFX_FNF_SOUND_BURST' },
  { label: 'Fire-and-forget: sound burst (silent)', nwscript: 'VFX_FNF_SOUND_BURST_SILENT' },
  { label: 'Fire-and-forget: spell fail, hand', nwscript: '293' },
  { label: 'Fire-and-forget: spell fail, head', nwscript: '292' },
  { label: 'Fire-and-forget: strike holy', nwscript: 'VFX_FNF_STRIKE_HOLY' },
  { label: 'Fire-and-forget: summon celestial', nwscript: 'VFX_FNF_SUMMON_CELESTIAL' },
  { label: 'Fire-and-forget: summon dragon', nwscript: 'VFX_FNF_SUMMONDRAGON' },
  { label: 'Fire-and-forget: summon epic undead', nwscript: 'VFX_FNF_SUMMON_EPIC_UNDEAD' },
  { label: 'Fire-and-forget: summon gate', nwscript: 'VFX_FNF_SUMMON_GATE' },
  { label: 'Fire-and-forget: summon monster 1', nwscript: 'VFX_FNF_SUMMON_MONSTER_1' },
  { label: 'Fire-and-forget: summon monster 2', nwscript: 'VFX_FNF_SUMMON_MONSTER_2' },
  { label: 'Fire-and-forget: summon monster 3', nwscript: 'VFX_FNF_SUMMON_MONSTER_3' },
  { label: 'Fire-and-forget: summon undead', nwscript: 'VFX_FNF_SUMMON_UNDEAD' },
  { label: 'Fire-and-forget: sunbeam', nwscript: 'VFX_FNF_SUNBEAM' },
  { label: 'Fire-and-forget: swinging blade', nwscript: 'VFX_FNF_SWINGING_BLADE' },
  { label: 'Fire-and-forget: teleport in', nwscript: '471' },
  { label: 'Fire-and-forget: teleport out', nwscript: '472' },
  { label: 'Fire-and-forget: time stop', nwscript: 'VFX_FNF_TIME_STOP' },
  { label: 'Fire-and-forget: undead dragon', nwscript: 'VFX_FNF_UNDEAD_DRAGON' },
  { label: 'Fire-and-forget: wail of the banshees', nwscript: 'VFX_FNF_WAIL_O_BANSHEES' },
  { label: 'Fire-and-forget: weird', nwscript: 'VFX_FNF_WEIRD' },
  { label: 'Fire-and-forget: word', nwscript: 'VFX_FNF_WORD' },
  { label: 'Impact: AC bonus', nwscript: 'VFX_IMP_AC_BONUS' },
  { label: 'Impact: acid l', nwscript: 'VFX_IMP_ACID_L' },
  { label: 'Impact: acid s', nwscript: 'VFX_IMP_ACID_S' },
  { label: 'Impact: Bigby\'s forceful hand', nwscript: 'VFX_IMP_BIGBYS_FORCEFUL_HAND' },
  { label: 'Impact: blind/deaf m', nwscript: 'VFX_IMP_BLIND_DEAF_M' },
  { label: 'Impact: breach', nwscript: 'VFX_IMP_BREACH' },
  { label: 'Impact: charm', nwscript: 'VFX_IMP_CHARM' },
  { label: 'Impact: clouds', nwscript: '133' },
  { label: 'Impact: cone of cold, head', nwscript: '490' },
  { label: 'Impact: confusion s', nwscript: 'VFX_IMP_CONFUSION_S' },
  { label: 'Impact: dazed s', nwscript: 'VFX_IMP_DAZED_S' },
  { label: 'Impact: death', nwscript: 'VFX_IMP_DEATH' },
  { label: 'Impact: death l', nwscript: 'VFX_IMP_DEATH_L' },
  { label: 'Impact: death ward', nwscript: 'VFX_IMP_DEATH_WARD' },
  { label: 'Impact: destruction', nwscript: 'VFX_IMP_DESTRUCTION' },
  { label: 'Impact: destruction, low', nwscript: '302' },
  { label: 'Impact: disease s', nwscript: 'VFX_IMP_DISEASE_S' },
  { label: 'Impact: dispel', nwscript: 'VFX_IMP_DISPEL' },
  { label: 'Impact: divine strike fire', nwscript: 'VFX_IMP_DIVINE_STRIKE_FIRE' },
  { label: 'Impact: divine strike holy', nwscript: 'VFX_IMP_DIVINE_STRIKE_HOLY' },
  { label: 'Impact: dominate s', nwscript: 'VFX_IMP_DOMINATE_S' },
  { label: 'Impact: doom', nwscript: 'VFX_IMP_DOOM' },
  { label: 'Impact: dust explosion', nwscript: 'VFX_IMP_DUST_EXPLOSION' },
  { label: 'Impact: elemental protection', nwscript: 'VFX_IMP_ELEMENTAL_PROTECTION' },
  { label: 'Impact: evil help', nwscript: 'VFX_IMP_EVIL_HELP' },
  { label: 'Impact: flame m', nwscript: 'VFX_IMP_FLAME_M' },
  { label: 'Impact: flame s', nwscript: 'VFX_IMP_FLAME_S' },
  { label: 'Impact: fortitude saving throw use', nwscript: 'VFX_IMP_FORTITUDE_SAVING_THROW_USE' },
  { label: 'Impact: frost l', nwscript: 'VFX_IMP_FROST_L' },
  { label: 'Impact: frost s', nwscript: 'VFX_IMP_FROST_S' },
  { label: 'Impact: globe use', nwscript: 'VFX_IMP_GLOBE_USE' },
  { label: 'Impact: good help', nwscript: 'VFX_IMP_GOOD_HELP' },
  { label: 'Impact: harm', nwscript: 'VFX_IMP_HARM' },
  { label: 'Impact: haste', nwscript: 'VFX_IMP_HASTE' },
  { label: 'Impact: head acid', nwscript: 'VFX_IMP_HEAD_ACID' },
  { label: 'Impact: head cold', nwscript: 'VFX_IMP_HEAD_COLD' },
  { label: 'Impact: head electricity', nwscript: 'VFX_IMP_HEAD_ELECTRICITY' },
  { label: 'Impact: head evil', nwscript: 'VFX_IMP_HEAD_EVIL' },
  { label: 'Impact: head fire', nwscript: 'VFX_IMP_HEAD_FIRE' },
  { label: 'Impact: head heal', nwscript: 'VFX_IMP_HEAD_HEAL' },
  { label: 'Impact: head holy', nwscript: 'VFX_IMP_HEAD_HOLY' },
  { label: 'Impact: head mind', nwscript: 'VFX_IMP_HEAD_MIND' },
  { label: 'Impact: head nature', nwscript: 'VFX_IMP_HEAD_NATURE' },
  { label: 'Impact: head odd', nwscript: 'VFX_IMP_HEAD_ODD' },
  { label: 'Impact: head sonic', nwscript: 'VFX_IMP_HEAD_SONIC' },
  { label: 'Impact: healing g', nwscript: 'VFX_IMP_HEALING_G' },
  { label: 'Impact: healing l', nwscript: 'VFX_IMP_HEALING_L' },
  { label: 'Impact: healing m', nwscript: 'VFX_IMP_HEALING_M' },
  { label: 'Impact: healing s', nwscript: 'VFX_IMP_HEALING_S' },
  { label: 'Impact: healing x', nwscript: 'VFX_IMP_HEALING_X' },
  { label: 'Impact: holy aid', nwscript: 'VFX_IMP_HOLY_AID' },
  { label: 'Impact: improve ability score', nwscript: 'VFX_IMP_IMPROVE_ABILITY_SCORE' },
  { label: 'Impact: knock', nwscript: 'VFX_IMP_KNOCK' },
  { label: 'Impact: lance shatter A', nwscript: '620' },
  { label: 'Impact: lance shatter B', nwscript: '621' },
  { label: 'Impact: lance shatter C', nwscript: '622' },
  { label: 'Impact: lightning m', nwscript: 'VFX_IMP_LIGHTNING_M' },
  { label: 'Impact: lightning s', nwscript: 'VFX_IMP_LIGHTNING_S' },
  { label: 'Impact: magblue', nwscript: 'VFX_IMP_MAGBLUE' },
  { label: 'Impact: magic protection', nwscript: 'VFX_IMP_MAGIC_PROTECTION' },
  { label: 'Impact: magic resistance use', nwscript: 'VFX_IMP_MAGIC_RESISTANCE_USE' },
  { label: 'Impact: magical vision', nwscript: 'VFX_IMP_MAGICAL_VISION' },
  { label: 'Impact: negative energy', nwscript: 'VFX_IMP_NEGATIVE_ENERGY' },
  { label: 'Impact: nightmare head hit', nwscript: 'VFX_IMP_NIGHTMARE_HEAD_HIT' },
  { label: 'Impact: PDK final stand', nwscript: 'VFX_IMP_PDK_FINAL_STAND' },
  { label: 'Impact: PDK generic head hit', nwscript: 'VFX_IMP_PDK_GENERIC_HEAD_HIT' },
  { label: 'Impact: PDK generic pulse', nwscript: 'VFX_IMP_PDK_GENERIC_PULSE' },
  { label: 'Impact: PDK heroic shield', nwscript: 'VFX_IMP_PDK_HEROIC_SHIELD' },
  { label: 'Impact: PDK inspire courage', nwscript: 'VFX_IMP_PDK_INSPIRE_COURAGE' },
  { label: 'Impact: PDK oath', nwscript: 'VFX_IMP_PDK_OATH' },
  { label: 'Impact: PDK rallying cry', nwscript: 'VFX_IMP_PDK_RALLYING_CRY' },
  { label: 'Impact: PDK wrath', nwscript: 'VFX_IMP_PDK_WRATH' },
  { label: 'Impact: poison s', nwscript: 'VFX_IMP_POISON_S' },
  { label: 'Impact: polymorph', nwscript: 'VFX_IMP_POLYMORPH' },
  { label: 'Impact: pulse bomb', nwscript: '469' },
  { label: 'Impact: pulse cold', nwscript: 'VFX_IMP_PULSE_COLD' },
  { label: 'Impact: pulse fire', nwscript: 'VFX_IMP_PULSE_FIRE' },
  { label: 'Impact: pulse holy', nwscript: 'VFX_IMP_PULSE_HOLY' },
  { label: 'Impact: pulse holy (silent)', nwscript: '462' },
  { label: 'Impact: pulse nature', nwscript: 'VFX_IMP_PULSE_NATURE' },
  { label: 'Impact: pulse negative', nwscript: 'VFX_IMP_PULSE_NEGATIVE' },
  { label: 'Impact: pulse water', nwscript: 'VFX_IMP_PULSE_WATER' },
  { label: 'Impact: pulse wind', nwscript: 'VFX_IMP_PULSE_WIND' },
  { label: 'Impact: raise dead', nwscript: 'VFX_IMP_RAISE_DEAD' },
  { label: 'Impact: reduce ability score', nwscript: 'VFX_IMP_REDUCE_ABILITY_SCORE' },
  { label: 'Impact: reflex save throw use', nwscript: 'VFX_IMP_REFLEX_SAVE_THROW_USE' },
  { label: 'Impact: remove condition', nwscript: 'VFX_IMP_REMOVE_CONDITION' },
  { label: 'Impact: restoration', nwscript: 'VFX_IMP_RESTORATION' },
  { label: 'Impact: restoration, greater', nwscript: 'VFX_IMP_RESTORATION_GREATER' },
  { label: 'Impact: restoration, lesser', nwscript: 'VFX_IMP_RESTORATION_LESSER' },
  { label: 'Impact: rock explode 1', nwscript: '135' },
  { label: 'Impact: rock explode 2', nwscript: '136' },
  { label: 'Impact: rocks up', nwscript: '137' },
  { label: 'Impact: silence', nwscript: 'VFX_IMP_SILENCE' },
  { label: 'Impact: silence (no sound)', nwscript: '470' },
  { label: 'Impact: sleep', nwscript: 'VFX_IMP_SLEEP' },
  { label: 'Impact: slow', nwscript: 'VFX_IMP_SLOW' },
  { label: 'Impact: sonic', nwscript: 'VFX_IMP_SONIC' },
  { label: 'Impact: spell mantle use', nwscript: 'VFX_IMP_SPELL_MANTLE_USE' },
  { label: 'Impact: spike trap', nwscript: 'VFX_IMP_SPIKE_TRAP' },
  { label: 'Impact: starburst green', nwscript: 'VFX_IMP_STARBURST_GREEN' },
  { label: 'Impact: starburst red', nwscript: 'VFX_IMP_STARBURST_RED' },
  { label: 'Impact: stun', nwscript: 'VFX_IMP_STUN' },
  { label: 'Impact: sunstrike', nwscript: 'VFX_IMP_SUNSTRIKE' },
  { label: 'Impact: super heroism', nwscript: 'VFX_IMP_SUPER_HEROISM' },
  { label: 'Impact: tornado', nwscript: 'VFX_IMP_TORNADO' },
  { label: 'Impact: unsummon', nwscript: 'VFX_IMP_UNSUMMON' },
  { label: 'Impact: wallspike', nwscript: 'VFX_IMP_WALLSPIKE' },
  { label: 'Impact: will saving throw use', nwscript: 'VFX_IMP_WILL_SAVING_THROW_USE' },
  { label: 'Impact: wind', nwscript: '134' },
];

